# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gitwin.ui'
#
# Created: Fri Dec 12 00:44:22 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GitWindow(object):
    def setupUi(self, GitWindow):
        GitWindow.setObjectName(_fromUtf8("GitWindow"))
        GitWindow.resize(526, 628)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GitWindow.sizePolicy().hasHeightForWidth())
        GitWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(GitWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget_buttonClose = QtGui.QWidget(self.centralwidget)
        self.widget_buttonClose.setObjectName(_fromUtf8("widget_buttonClose"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_buttonClose)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.button_close = QtGui.QPushButton(self.widget_buttonClose)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setMinimumSize(QtCore.QSize(100, 25))
        self.button_close.setMaximumSize(QtCore.QSize(100, 25))
        self.button_close.setDefault(True)
        self.button_close.setObjectName(_fromUtf8("button_close"))
        self.gridLayout_2.addWidget(self.button_close, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_buttonClose, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(410, 380))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_search = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_search.sizePolicy().hasHeightForWidth())
        self.tab_search.setSizePolicy(sizePolicy)
        self.tab_search.setObjectName(_fromUtf8("tab_search"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_search)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.tabWidget_search = QtGui.QTabWidget(self.tab_search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_search.sizePolicy().hasHeightForWidth())
        self.tabWidget_search.setSizePolicy(sizePolicy)
        self.tabWidget_search.setMinimumSize(QtCore.QSize(0, 100))
        self.tabWidget_search.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tabWidget_search.setObjectName(_fromUtf8("tabWidget_search"))
        self.tab_search_01 = QtGui.QWidget()
        self.tab_search_01.setObjectName(_fromUtf8("tab_search_01"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_search_01)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.widget_int = QtGui.QWidget(self.tab_search_01)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_int.sizePolicy().hasHeightForWidth())
        self.widget_int.setSizePolicy(sizePolicy)
        self.widget_int.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_int.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_int.setObjectName(_fromUtf8("widget_int"))
        self.gridLayout_16 = QtGui.QGridLayout(self.widget_int)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_timeFrom = QtGui.QLabel(self.widget_int)
        self.label_timeFrom.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timeFrom.sizePolicy().hasHeightForWidth())
        self.label_timeFrom.setSizePolicy(sizePolicy)
        self.label_timeFrom.setMinimumSize(QtCore.QSize(30, 25))
        self.label_timeFrom.setMaximumSize(QtCore.QSize(30, 25))
        self.label_timeFrom.setObjectName(_fromUtf8("label_timeFrom"))
        self.gridLayout_16.addWidget(self.label_timeFrom, 1, 0, 1, 1)
        self.timeEdit_from = QtGui.QDateTimeEdit(self.widget_int)
        self.timeEdit_from.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_from.sizePolicy().hasHeightForWidth())
        self.timeEdit_from.setSizePolicy(sizePolicy)
        self.timeEdit_from.setMinimumSize(QtCore.QSize(0, 25))
        self.timeEdit_from.setMaximumSize(QtCore.QSize(16777215, 25))
        self.timeEdit_from.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_from.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_from.setCalendarPopup(True)
        self.timeEdit_from.setObjectName(_fromUtf8("timeEdit_from"))
        self.gridLayout_16.addWidget(self.timeEdit_from, 1, 1, 1, 1)
        self.label_timeTo = QtGui.QLabel(self.widget_int)
        self.label_timeTo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timeTo.sizePolicy().hasHeightForWidth())
        self.label_timeTo.setSizePolicy(sizePolicy)
        self.label_timeTo.setMinimumSize(QtCore.QSize(30, 25))
        self.label_timeTo.setMaximumSize(QtCore.QSize(30, 25))
        self.label_timeTo.setObjectName(_fromUtf8("label_timeTo"))
        self.gridLayout_16.addWidget(self.label_timeTo, 1, 2, 1, 1)
        self.timeEdit_to = QtGui.QDateTimeEdit(self.widget_int)
        self.timeEdit_to.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_to.sizePolicy().hasHeightForWidth())
        self.timeEdit_to.setSizePolicy(sizePolicy)
        self.timeEdit_to.setMinimumSize(QtCore.QSize(0, 25))
        self.timeEdit_to.setMaximumSize(QtCore.QSize(16777215, 25))
        self.timeEdit_to.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_to.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_to.setCalendarPopup(True)
        self.timeEdit_to.setObjectName(_fromUtf8("timeEdit_to"))
        self.gridLayout_16.addWidget(self.timeEdit_to, 1, 3, 1, 1)
        self.label_titleInt = QtGui.QLabel(self.widget_int)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titleInt.sizePolicy().hasHeightForWidth())
        self.label_titleInt.setSizePolicy(sizePolicy)
        self.label_titleInt.setMinimumSize(QtCore.QSize(0, 25))
        self.label_titleInt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_titleInt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titleInt.setObjectName(_fromUtf8("label_titleInt"))
        self.gridLayout_16.addWidget(self.label_titleInt, 0, 0, 1, 4)
        self.gridLayout_17.addWidget(self.widget_int, 0, 0, 1, 1)
        self.tabWidget_search.addTab(self.tab_search_01, _fromUtf8(""))
        self.tab_search_02 = QtGui.QWidget()
        self.tab_search_02.setObjectName(_fromUtf8("tab_search_02"))
        self.gridLayout_19 = QtGui.QGridLayout(self.tab_search_02)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.widget_times = QtGui.QWidget(self.tab_search_02)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_times.sizePolicy().hasHeightForWidth())
        self.widget_times.setSizePolicy(sizePolicy)
        self.widget_times.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_times.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_times.setObjectName(_fromUtf8("widget_times"))
        self.gridLayout_20 = QtGui.QGridLayout(self.widget_times)
        self.gridLayout_20.setMargin(0)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_times = QtGui.QLabel(self.widget_times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_times.sizePolicy().hasHeightForWidth())
        self.label_times.setSizePolicy(sizePolicy)
        self.label_times.setMinimumSize(QtCore.QSize(120, 25))
        self.label_times.setMaximumSize(QtCore.QSize(120, 25))
        self.label_times.setObjectName(_fromUtf8("label_times"))
        self.gridLayout_20.addWidget(self.label_times, 1, 0, 1, 1)
        self.spinBox_times = QtGui.QSpinBox(self.widget_times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_times.sizePolicy().hasHeightForWidth())
        self.spinBox_times.setSizePolicy(sizePolicy)
        self.spinBox_times.setMinimumSize(QtCore.QSize(120, 25))
        self.spinBox_times.setMaximumSize(QtCore.QSize(16777215, 25))
        self.spinBox_times.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_times.setMinimum(1)
        self.spinBox_times.setMaximum(999)
        self.spinBox_times.setObjectName(_fromUtf8("spinBox_times"))
        self.gridLayout_20.addWidget(self.spinBox_times, 1, 1, 1, 1)
        self.label_titleTimes = QtGui.QLabel(self.widget_times)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titleTimes.sizePolicy().hasHeightForWidth())
        self.label_titleTimes.setSizePolicy(sizePolicy)
        self.label_titleTimes.setMinimumSize(QtCore.QSize(0, 25))
        self.label_titleTimes.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_titleTimes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titleTimes.setObjectName(_fromUtf8("label_titleTimes"))
        self.gridLayout_20.addWidget(self.label_titleTimes, 0, 0, 1, 2)
        self.gridLayout_19.addWidget(self.widget_times, 0, 0, 1, 1)
        self.tabWidget_search.addTab(self.tab_search_02, _fromUtf8(""))
        self.tab_search_03 = QtGui.QWidget()
        self.tab_search_03.setObjectName(_fromUtf8("tab_search_03"))
        self.gridLayout_21 = QtGui.QGridLayout(self.tab_search_03)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.widget_date = QtGui.QWidget(self.tab_search_03)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_date.sizePolicy().hasHeightForWidth())
        self.widget_date.setSizePolicy(sizePolicy)
        self.widget_date.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_date.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_date.setObjectName(_fromUtf8("widget_date"))
        self.gridLayout_18 = QtGui.QGridLayout(self.widget_date)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_date = QtGui.QLabel(self.widget_date)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date.sizePolicy().hasHeightForWidth())
        self.label_date.setSizePolicy(sizePolicy)
        self.label_date.setMinimumSize(QtCore.QSize(100, 25))
        self.label_date.setMaximumSize(QtCore.QSize(100, 25))
        self.label_date.setObjectName(_fromUtf8("label_date"))
        self.gridLayout_18.addWidget(self.label_date, 1, 0, 1, 1)
        self.dateEdit_date = QtGui.QDateEdit(self.widget_date)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_date.sizePolicy().hasHeightForWidth())
        self.dateEdit_date.setSizePolicy(sizePolicy)
        self.dateEdit_date.setMinimumSize(QtCore.QSize(150, 25))
        self.dateEdit_date.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dateEdit_date.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_date.setDate(QtCore.QDate(2013, 1, 1))
        self.dateEdit_date.setCalendarPopup(True)
        self.dateEdit_date.setObjectName(_fromUtf8("dateEdit_date"))
        self.gridLayout_18.addWidget(self.dateEdit_date, 1, 1, 1, 1)
        self.label_titleDate = QtGui.QLabel(self.widget_date)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titleDate.sizePolicy().hasHeightForWidth())
        self.label_titleDate.setSizePolicy(sizePolicy)
        self.label_titleDate.setMinimumSize(QtCore.QSize(0, 25))
        self.label_titleDate.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_titleDate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titleDate.setObjectName(_fromUtf8("label_titleDate"))
        self.gridLayout_18.addWidget(self.label_titleDate, 0, 0, 1, 2)
        self.gridLayout_21.addWidget(self.widget_date, 0, 0, 1, 1)
        self.tabWidget_search.addTab(self.tab_search_03, _fromUtf8(""))
        self.gridLayout_23.addWidget(self.tabWidget_search, 0, 0, 1, 1)
        self.list_commit = QtGui.QListWidget(self.tab_search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_commit.sizePolicy().hasHeightForWidth())
        self.list_commit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.list_commit.setFont(font)
        self.list_commit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.list_commit.setObjectName(_fromUtf8("list_commit"))
        self.gridLayout_23.addWidget(self.list_commit, 2, 0, 1, 1)
        self.widget_buttonGet = QtGui.QWidget(self.tab_search)
        self.widget_buttonGet.setObjectName(_fromUtf8("widget_buttonGet"))
        self.gridLayout_22 = QtGui.QGridLayout(self.widget_buttonGet)
        self.gridLayout_22.setMargin(0)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem1, 0, 0, 1, 1)
        self.button_get = QtGui.QPushButton(self.widget_buttonGet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get.sizePolicy().hasHeightForWidth())
        self.button_get.setSizePolicy(sizePolicy)
        self.button_get.setMinimumSize(QtCore.QSize(100, 25))
        self.button_get.setMaximumSize(QtCore.QSize(100, 25))
        self.button_get.setDefault(True)
        self.button_get.setObjectName(_fromUtf8("button_get"))
        self.gridLayout_22.addWidget(self.button_get, 0, 1, 1, 1)
        self.gridLayout_23.addWidget(self.widget_buttonGet, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_search, _fromUtf8(""))
        self.tab_oneFile = QtGui.QWidget()
        self.tab_oneFile.setObjectName(_fromUtf8("tab_oneFile"))
        self.gridLayout_29 = QtGui.QGridLayout(self.tab_oneFile)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.box_file = QtGui.QComboBox(self.tab_oneFile)
        self.box_file.setMinimumSize(QtCore.QSize(0, 25))
        self.box_file.setObjectName(_fromUtf8("box_file"))
        self.gridLayout_29.addWidget(self.box_file, 0, 0, 1, 1)
        self.list_commit_oneFile = QtGui.QListWidget(self.tab_oneFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_commit_oneFile.sizePolicy().hasHeightForWidth())
        self.list_commit_oneFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.list_commit_oneFile.setFont(font)
        self.list_commit_oneFile.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.list_commit_oneFile.setObjectName(_fromUtf8("list_commit_oneFile"))
        self.gridLayout_29.addWidget(self.list_commit_oneFile, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_oneFile, _fromUtf8(""))
        self.tab_status = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_status.sizePolicy().hasHeightForWidth())
        self.tab_status.setSizePolicy(sizePolicy)
        self.tab_status.setObjectName(_fromUtf8("tab_status"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_status)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget_buttonsStatus = QtGui.QWidget(self.tab_status)
        self.widget_buttonsStatus.setObjectName(_fromUtf8("widget_buttonsStatus"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_buttonsStatus)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.button_createCommit = QtGui.QPushButton(self.widget_buttonsStatus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_createCommit.sizePolicy().hasHeightForWidth())
        self.button_createCommit.setSizePolicy(sizePolicy)
        self.button_createCommit.setMinimumSize(QtCore.QSize(125, 25))
        self.button_createCommit.setMaximumSize(QtCore.QSize(125, 25))
        self.button_createCommit.setDefault(True)
        self.button_createCommit.setObjectName(_fromUtf8("button_createCommit"))
        self.gridLayout_3.addWidget(self.button_createCommit, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.button_status = QtGui.QPushButton(self.widget_buttonsStatus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_status.sizePolicy().hasHeightForWidth())
        self.button_status.setSizePolicy(sizePolicy)
        self.button_status.setMinimumSize(QtCore.QSize(125, 25))
        self.button_status.setMaximumSize(QtCore.QSize(100, 25))
        self.button_status.setDefault(True)
        self.button_status.setObjectName(_fromUtf8("button_status"))
        self.gridLayout_3.addWidget(self.button_status, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.widget_buttonsStatus, 0, 0, 1, 1)
        self.text_status = QtGui.QTextBrowser(self.tab_status)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_status.sizePolicy().hasHeightForWidth())
        self.text_status.setSizePolicy(sizePolicy)
        self.text_status.setMinimumSize(QtCore.QSize(411, 311))
        self.text_status.setObjectName(_fromUtf8("text_status"))
        self.gridLayout_4.addWidget(self.text_status, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_status, _fromUtf8(""))
        self.tab_ignore = QtGui.QWidget()
        self.tab_ignore.setObjectName(_fromUtf8("tab_ignore"))
        self.gridLayout_28 = QtGui.QGridLayout(self.tab_ignore)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.widget_buttonRefresh = QtGui.QWidget(self.tab_ignore)
        self.widget_buttonRefresh.setObjectName(_fromUtf8("widget_buttonRefresh"))
        self.gridLayout_24 = QtGui.QGridLayout(self.widget_buttonRefresh)
        self.gridLayout_24.setMargin(0)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        spacerItem3 = QtGui.QSpacerItem(362, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem3, 0, 0, 1, 1)
        self.button_refreshIgnore = QtGui.QPushButton(self.widget_buttonRefresh)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_refreshIgnore.sizePolicy().hasHeightForWidth())
        self.button_refreshIgnore.setSizePolicy(sizePolicy)
        self.button_refreshIgnore.setMinimumSize(QtCore.QSize(100, 25))
        self.button_refreshIgnore.setMaximumSize(QtCore.QSize(100, 25))
        self.button_refreshIgnore.setDefault(True)
        self.button_refreshIgnore.setObjectName(_fromUtf8("button_refreshIgnore"))
        self.gridLayout_24.addWidget(self.button_refreshIgnore, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.widget_buttonRefresh, 0, 0, 1, 1)
        self.widget_addIgnore = QtGui.QWidget(self.tab_ignore)
        self.widget_addIgnore.setObjectName(_fromUtf8("widget_addIgnore"))
        self.gridLayout_25 = QtGui.QGridLayout(self.widget_addIgnore)
        self.gridLayout_25.setMargin(0)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.lineEdit_addIgnore = QtGui.QLineEdit(self.widget_addIgnore)
        self.lineEdit_addIgnore.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_addIgnore.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_addIgnore.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_addIgnore.setObjectName(_fromUtf8("lineEdit_addIgnore"))
        self.gridLayout_25.addWidget(self.lineEdit_addIgnore, 0, 0, 1, 1)
        self.button_addIgnore = QtGui.QPushButton(self.widget_addIgnore)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_addIgnore.sizePolicy().hasHeightForWidth())
        self.button_addIgnore.setSizePolicy(sizePolicy)
        self.button_addIgnore.setMinimumSize(QtCore.QSize(100, 25))
        self.button_addIgnore.setMaximumSize(QtCore.QSize(100, 25))
        self.button_addIgnore.setDefault(True)
        self.button_addIgnore.setObjectName(_fromUtf8("button_addIgnore"))
        self.gridLayout_25.addWidget(self.button_addIgnore, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.widget_addIgnore, 1, 0, 1, 1)
        self.list_ignoreList = QtGui.QListWidget(self.tab_ignore)
        self.list_ignoreList.setObjectName(_fromUtf8("list_ignoreList"))
        self.gridLayout_28.addWidget(self.list_ignoreList, 2, 0, 1, 1)
        self.widget_buttonDelete = QtGui.QWidget(self.tab_ignore)
        self.widget_buttonDelete.setObjectName(_fromUtf8("widget_buttonDelete"))
        self.gridLayout_26 = QtGui.QGridLayout(self.widget_buttonDelete)
        self.gridLayout_26.setMargin(0)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.button_deleteIgnore = QtGui.QPushButton(self.widget_buttonDelete)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_deleteIgnore.sizePolicy().hasHeightForWidth())
        self.button_deleteIgnore.setSizePolicy(sizePolicy)
        self.button_deleteIgnore.setMinimumSize(QtCore.QSize(130, 25))
        self.button_deleteIgnore.setMaximumSize(QtCore.QSize(130, 25))
        self.button_deleteIgnore.setDefault(True)
        self.button_deleteIgnore.setObjectName(_fromUtf8("button_deleteIgnore"))
        self.gridLayout_26.addWidget(self.button_deleteIgnore, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_28.addWidget(self.widget_buttonDelete, 3, 0, 1, 1)
        self.widget_buttonApply = QtGui.QWidget(self.tab_ignore)
        self.widget_buttonApply.setObjectName(_fromUtf8("widget_buttonApply"))
        self.gridLayout_27 = QtGui.QGridLayout(self.widget_buttonApply)
        self.gridLayout_27.setMargin(0)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        spacerItem5 = QtGui.QSpacerItem(362, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem5, 0, 0, 1, 1)
        self.button_applyIgnore = QtGui.QPushButton(self.widget_buttonApply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_applyIgnore.sizePolicy().hasHeightForWidth())
        self.button_applyIgnore.setSizePolicy(sizePolicy)
        self.button_applyIgnore.setMinimumSize(QtCore.QSize(100, 25))
        self.button_applyIgnore.setMaximumSize(QtCore.QSize(100, 25))
        self.button_applyIgnore.setDefault(True)
        self.button_applyIgnore.setObjectName(_fromUtf8("button_applyIgnore"))
        self.gridLayout_27.addWidget(self.button_applyIgnore, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.widget_buttonApply, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_ignore, _fromUtf8(""))
        self.tab_submodules = QtGui.QWidget()
        self.tab_submodules.setObjectName(_fromUtf8("tab_submodules"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_submodules)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layout_addSubmodule = QtGui.QHBoxLayout()
        self.layout_addSubmodule.setObjectName(_fromUtf8("layout_addSubmodule"))
        self.lineEdit_addSubmodule = QtGui.QLineEdit(self.tab_submodules)
        self.lineEdit_addSubmodule.setObjectName(_fromUtf8("lineEdit_addSubmodule"))
        self.layout_addSubmodule.addWidget(self.lineEdit_addSubmodule)
        self.pushButton_addSubmodule = QtGui.QPushButton(self.tab_submodules)
        self.pushButton_addSubmodule.setObjectName(_fromUtf8("pushButton_addSubmodule"))
        self.layout_addSubmodule.addWidget(self.pushButton_addSubmodule)
        self.verticalLayout.addLayout(self.layout_addSubmodule)
        self.listWidget_submodule = QtGui.QListWidget(self.tab_submodules)
        self.listWidget_submodule.setObjectName(_fromUtf8("listWidget_submodule"))
        self.verticalLayout.addWidget(self.listWidget_submodule)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.pushButton_refreshSubmodules = QtGui.QPushButton(self.tab_submodules)
        self.pushButton_refreshSubmodules.setObjectName(_fromUtf8("pushButton_refreshSubmodules"))
        self.horizontalLayout.addWidget(self.pushButton_refreshSubmodules)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_submodules, _fromUtf8(""))
        self.tab_merge = QtGui.QWidget()
        self.tab_merge.setObjectName(_fromUtf8("tab_merge"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_merge)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_merge = QtGui.QLabel(self.tab_merge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_merge.sizePolicy().hasHeightForWidth())
        self.label_merge.setSizePolicy(sizePolicy)
        self.label_merge.setMinimumSize(QtCore.QSize(0, 50))
        self.label_merge.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_merge.setObjectName(_fromUtf8("label_merge"))
        self.gridLayout_13.addWidget(self.label_merge, 0, 0, 1, 1)
        self.tabWidget_merge = QtGui.QTabWidget(self.tab_merge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_merge.sizePolicy().hasHeightForWidth())
        self.tabWidget_merge.setSizePolicy(sizePolicy)
        self.tabWidget_merge.setMinimumSize(QtCore.QSize(0, 130))
        self.tabWidget_merge.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tabWidget_merge.setObjectName(_fromUtf8("tabWidget_merge"))
        self.tab_merge_01 = QtGui.QWidget()
        self.tab_merge_01.setObjectName(_fromUtf8("tab_merge_01"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_merge_01)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.widget_search = QtGui.QWidget(self.tab_merge_01)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_search.sizePolicy().hasHeightForWidth())
        self.widget_search.setSizePolicy(sizePolicy)
        self.widget_search.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_search.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_search.setObjectName(_fromUtf8("widget_search"))
        self.gridLayout_11 = QtGui.QGridLayout(self.widget_search)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.box_old = QtGui.QComboBox(self.widget_search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_old.sizePolicy().hasHeightForWidth())
        self.box_old.setSizePolicy(sizePolicy)
        self.box_old.setMinimumSize(QtCore.QSize(200, 25))
        self.box_old.setMaximumSize(QtCore.QSize(16777215, 25))
        self.box_old.setObjectName(_fromUtf8("box_old"))
        self.gridLayout_11.addWidget(self.box_old, 1, 1, 1, 1)
        self.label_titleSearch = QtGui.QLabel(self.widget_search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titleSearch.sizePolicy().hasHeightForWidth())
        self.label_titleSearch.setSizePolicy(sizePolicy)
        self.label_titleSearch.setMinimumSize(QtCore.QSize(0, 25))
        self.label_titleSearch.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_titleSearch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titleSearch.setObjectName(_fromUtf8("label_titleSearch"))
        self.gridLayout_11.addWidget(self.label_titleSearch, 0, 0, 1, 2)
        self.label_old01 = QtGui.QLabel(self.widget_search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_old01.sizePolicy().hasHeightForWidth())
        self.label_old01.setSizePolicy(sizePolicy)
        self.label_old01.setMinimumSize(QtCore.QSize(100, 25))
        self.label_old01.setMaximumSize(QtCore.QSize(100, 25))
        self.label_old01.setObjectName(_fromUtf8("label_old01"))
        self.gridLayout_11.addWidget(self.label_old01, 1, 0, 1, 1)
        self.box_new = QtGui.QComboBox(self.widget_search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_new.sizePolicy().hasHeightForWidth())
        self.box_new.setSizePolicy(sizePolicy)
        self.box_new.setMinimumSize(QtCore.QSize(200, 25))
        self.box_new.setMaximumSize(QtCore.QSize(16777215, 25))
        self.box_new.setObjectName(_fromUtf8("box_new"))
        self.gridLayout_11.addWidget(self.box_new, 2, 1, 1, 1)
        self.label_new01 = QtGui.QLabel(self.widget_search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_new01.sizePolicy().hasHeightForWidth())
        self.label_new01.setSizePolicy(sizePolicy)
        self.label_new01.setMinimumSize(QtCore.QSize(100, 25))
        self.label_new01.setMaximumSize(QtCore.QSize(100, 25))
        self.label_new01.setObjectName(_fromUtf8("label_new01"))
        self.gridLayout_11.addWidget(self.label_new01, 2, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_search, 0, 0, 1, 1)
        self.tabWidget_merge.addTab(self.tab_merge_01, _fromUtf8(""))
        self.tab_merge_02 = QtGui.QWidget()
        self.tab_merge_02.setObjectName(_fromUtf8("tab_merge_02"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_merge_02)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.widget_browse = QtGui.QWidget(self.tab_merge_02)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_browse.sizePolicy().hasHeightForWidth())
        self.widget_browse.setSizePolicy(sizePolicy)
        self.widget_browse.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_browse.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_browse.setObjectName(_fromUtf8("widget_browse"))
        self.gridLayout_14 = QtGui.QGridLayout(self.widget_browse)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_old02 = QtGui.QLabel(self.widget_browse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_old02.sizePolicy().hasHeightForWidth())
        self.label_old02.setSizePolicy(sizePolicy)
        self.label_old02.setMinimumSize(QtCore.QSize(100, 25))
        self.label_old02.setMaximumSize(QtCore.QSize(100, 25))
        self.label_old02.setObjectName(_fromUtf8("label_old02"))
        self.gridLayout_14.addWidget(self.label_old02, 1, 0, 1, 1)
        self.lineEdit_old = QtGui.QLineEdit(self.widget_browse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_old.sizePolicy().hasHeightForWidth())
        self.lineEdit_old.setSizePolicy(sizePolicy)
        self.lineEdit_old.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_old.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_old.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_old.setObjectName(_fromUtf8("lineEdit_old"))
        self.gridLayout_14.addWidget(self.lineEdit_old, 1, 1, 1, 1)
        self.button_browseOld = QtGui.QPushButton(self.widget_browse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browseOld.sizePolicy().hasHeightForWidth())
        self.button_browseOld.setSizePolicy(sizePolicy)
        self.button_browseOld.setMinimumSize(QtCore.QSize(75, 25))
        self.button_browseOld.setMaximumSize(QtCore.QSize(75, 25))
        self.button_browseOld.setDefault(True)
        self.button_browseOld.setObjectName(_fromUtf8("button_browseOld"))
        self.gridLayout_14.addWidget(self.button_browseOld, 1, 2, 1, 1)
        self.label_new02 = QtGui.QLabel(self.widget_browse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_new02.sizePolicy().hasHeightForWidth())
        self.label_new02.setSizePolicy(sizePolicy)
        self.label_new02.setMinimumSize(QtCore.QSize(100, 25))
        self.label_new02.setMaximumSize(QtCore.QSize(100, 25))
        self.label_new02.setObjectName(_fromUtf8("label_new02"))
        self.gridLayout_14.addWidget(self.label_new02, 2, 0, 1, 1)
        self.lineEdit_new = QtGui.QLineEdit(self.widget_browse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_new.sizePolicy().hasHeightForWidth())
        self.lineEdit_new.setSizePolicy(sizePolicy)
        self.lineEdit_new.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_new.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_new.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_new.setObjectName(_fromUtf8("lineEdit_new"))
        self.gridLayout_14.addWidget(self.lineEdit_new, 2, 1, 1, 1)
        self.button_browseNew = QtGui.QPushButton(self.widget_browse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browseNew.sizePolicy().hasHeightForWidth())
        self.button_browseNew.setSizePolicy(sizePolicy)
        self.button_browseNew.setMinimumSize(QtCore.QSize(75, 25))
        self.button_browseNew.setMaximumSize(QtCore.QSize(75, 25))
        self.button_browseNew.setDefault(True)
        self.button_browseNew.setObjectName(_fromUtf8("button_browseNew"))
        self.gridLayout_14.addWidget(self.button_browseNew, 2, 2, 1, 1)
        self.label_titleBrowse = QtGui.QLabel(self.widget_browse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_titleBrowse.sizePolicy().hasHeightForWidth())
        self.label_titleBrowse.setSizePolicy(sizePolicy)
        self.label_titleBrowse.setMinimumSize(QtCore.QSize(0, 25))
        self.label_titleBrowse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titleBrowse.setObjectName(_fromUtf8("label_titleBrowse"))
        self.gridLayout_14.addWidget(self.label_titleBrowse, 0, 0, 1, 3)
        self.gridLayout_15.addWidget(self.widget_browse, 0, 0, 1, 1)
        self.tabWidget_merge.addTab(self.tab_merge_02, _fromUtf8(""))
        self.gridLayout_13.addWidget(self.tabWidget_merge, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem7, 2, 0, 1, 1)
        self.widget_buttonsApply = QtGui.QWidget(self.tab_merge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_buttonsApply.sizePolicy().hasHeightForWidth())
        self.widget_buttonsApply.setSizePolicy(sizePolicy)
        self.widget_buttonsApply.setMinimumSize(QtCore.QSize(0, 62))
        self.widget_buttonsApply.setMaximumSize(QtCore.QSize(16777215, 62))
        self.widget_buttonsApply.setObjectName(_fromUtf8("widget_buttonsApply"))
        self.gridLayout_10 = QtGui.QGridLayout(self.widget_buttonsApply)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        spacerItem8 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem8, 1, 0, 1, 1)
        self.button_patch = QtGui.QPushButton(self.widget_buttonsApply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_patch.sizePolicy().hasHeightForWidth())
        self.button_patch.setSizePolicy(sizePolicy)
        self.button_patch.setMinimumSize(QtCore.QSize(150, 25))
        self.button_patch.setMaximumSize(QtCore.QSize(150, 25))
        self.button_patch.setDefault(True)
        self.button_patch.setObjectName(_fromUtf8("button_patch"))
        self.gridLayout_10.addWidget(self.button_patch, 1, 1, 1, 2)
        spacerItem9 = QtGui.QSpacerItem(86, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem9, 2, 0, 1, 2)
        self.button_applyPatch = QtGui.QPushButton(self.widget_buttonsApply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_applyPatch.sizePolicy().hasHeightForWidth())
        self.button_applyPatch.setSizePolicy(sizePolicy)
        self.button_applyPatch.setMinimumSize(QtCore.QSize(100, 25))
        self.button_applyPatch.setMaximumSize(QtCore.QSize(100, 25))
        self.button_applyPatch.setDefault(True)
        self.button_applyPatch.setObjectName(_fromUtf8("button_applyPatch"))
        self.gridLayout_10.addWidget(self.button_applyPatch, 2, 2, 1, 1)
        self.gridLayout_13.addWidget(self.widget_buttonsApply, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_merge, _fromUtf8(""))
        self.tab_reset = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_reset.sizePolicy().hasHeightForWidth())
        self.tab_reset.setSizePolicy(sizePolicy)
        self.tab_reset.setObjectName(_fromUtf8("tab_reset"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_reset)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_text1 = QtGui.QLabel(self.tab_reset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text1.sizePolicy().hasHeightForWidth())
        self.label_text1.setSizePolicy(sizePolicy)
        self.label_text1.setMinimumSize(QtCore.QSize(401, 25))
        self.label_text1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_text1.setObjectName(_fromUtf8("label_text1"))
        self.gridLayout_9.addWidget(self.label_text1, 0, 0, 1, 1)
        self.label_text2 = QtGui.QLabel(self.tab_reset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text2.sizePolicy().hasHeightForWidth())
        self.label_text2.setSizePolicy(sizePolicy)
        self.label_text2.setMinimumSize(QtCore.QSize(401, 25))
        self.label_text2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_text2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text2.setObjectName(_fromUtf8("label_text2"))
        self.gridLayout_9.addWidget(self.label_text2, 1, 0, 1, 1)
        self.label_text3 = QtGui.QLabel(self.tab_reset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text3.sizePolicy().hasHeightForWidth())
        self.label_text3.setSizePolicy(sizePolicy)
        self.label_text3.setMinimumSize(QtCore.QSize(401, 25))
        self.label_text3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_text3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text3.setObjectName(_fromUtf8("label_text3"))
        self.gridLayout_9.addWidget(self.label_text3, 2, 0, 1, 1)
        self.label_text4 = QtGui.QLabel(self.tab_reset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text4.sizePolicy().hasHeightForWidth())
        self.label_text4.setSizePolicy(sizePolicy)
        self.label_text4.setMinimumSize(QtCore.QSize(401, 25))
        self.label_text4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_text4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text4.setObjectName(_fromUtf8("label_text4"))
        self.gridLayout_9.addWidget(self.label_text4, 3, 0, 1, 1)
        self.widget_idCommit = QtGui.QWidget(self.tab_reset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_idCommit.sizePolicy().hasHeightForWidth())
        self.widget_idCommit.setSizePolicy(sizePolicy)
        self.widget_idCommit.setObjectName(_fromUtf8("widget_idCommit"))
        self.gridLayout_8 = QtGui.QGridLayout(self.widget_idCommit)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_id = QtGui.QLabel(self.widget_idCommit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_id.sizePolicy().hasHeightForWidth())
        self.label_id.setSizePolicy(sizePolicy)
        self.label_id.setMinimumSize(QtCore.QSize(175, 25))
        self.label_id.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_id.setObjectName(_fromUtf8("label_id"))
        self.gridLayout_8.addWidget(self.label_id, 0, 0, 1, 1)
        self.lineEdit_id = QtGui.QLineEdit(self.widget_idCommit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id.sizePolicy().hasHeightForWidth())
        self.lineEdit_id.setSizePolicy(sizePolicy)
        self.lineEdit_id.setMinimumSize(QtCore.QSize(175, 25))
        self.lineEdit_id.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_id.setObjectName(_fromUtf8("lineEdit_id"))
        self.gridLayout_8.addWidget(self.lineEdit_id, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.widget_idCommit, 4, 0, 1, 1)
        self.widget_typeReset = QtGui.QWidget(self.tab_reset)
        self.widget_typeReset.setObjectName(_fromUtf8("widget_typeReset"))
        self.gridLayout_7 = QtGui.QGridLayout(self.widget_typeReset)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_typeReset = QtGui.QLabel(self.widget_typeReset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_typeReset.sizePolicy().hasHeightForWidth())
        self.label_typeReset.setSizePolicy(sizePolicy)
        self.label_typeReset.setMinimumSize(QtCore.QSize(100, 25))
        self.label_typeReset.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_typeReset.setObjectName(_fromUtf8("label_typeReset"))
        self.gridLayout_7.addWidget(self.label_typeReset, 0, 0, 1, 1)
        self.box_typeReset = QtGui.QComboBox(self.widget_typeReset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_typeReset.sizePolicy().hasHeightForWidth())
        self.box_typeReset.setSizePolicy(sizePolicy)
        self.box_typeReset.setMinimumSize(QtCore.QSize(160, 25))
        self.box_typeReset.setMaximumSize(QtCore.QSize(16777215, 25))
        self.box_typeReset.setObjectName(_fromUtf8("box_typeReset"))
        self.box_typeReset.addItem(_fromUtf8(""))
        self.box_typeReset.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.box_typeReset, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.widget_typeReset, 5, 0, 1, 1)
        self.widget_fileName = QtGui.QWidget(self.tab_reset)
        self.widget_fileName.setObjectName(_fromUtf8("widget_fileName"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget_fileName)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.box_filename = QtGui.QComboBox(self.widget_fileName)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_filename.sizePolicy().hasHeightForWidth())
        self.box_filename.setSizePolicy(sizePolicy)
        self.box_filename.setMinimumSize(QtCore.QSize(0, 25))
        self.box_filename.setMaximumSize(QtCore.QSize(16777215, 25))
        self.box_filename.setObjectName(_fromUtf8("box_filename"))
        self.gridLayout_6.addWidget(self.box_filename, 0, 1, 1, 1)
        self.label_filename = QtGui.QLabel(self.widget_fileName)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filename.sizePolicy().hasHeightForWidth())
        self.label_filename.setSizePolicy(sizePolicy)
        self.label_filename.setMinimumSize(QtCore.QSize(120, 25))
        self.label_filename.setMaximumSize(QtCore.QSize(0, 25))
        self.label_filename.setObjectName(_fromUtf8("label_filename"))
        self.gridLayout_6.addWidget(self.label_filename, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.widget_fileName, 6, 0, 1, 1)
        self.widget_buttonsReset = QtGui.QWidget(self.tab_reset)
        self.widget_buttonsReset.setObjectName(_fromUtf8("widget_buttonsReset"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_buttonsReset)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.button_refresh = QtGui.QPushButton(self.widget_buttonsReset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_refresh.sizePolicy().hasHeightForWidth())
        self.button_refresh.setSizePolicy(sizePolicy)
        self.button_refresh.setMinimumSize(QtCore.QSize(135, 25))
        self.button_refresh.setMaximumSize(QtCore.QSize(135, 25))
        self.button_refresh.setDefault(True)
        self.button_refresh.setObjectName(_fromUtf8("button_refresh"))
        self.gridLayout_5.addWidget(self.button_refresh, 0, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 0, 1, 1, 1)
        self.button_reset = QtGui.QPushButton(self.widget_buttonsReset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_reset.sizePolicy().hasHeightForWidth())
        self.button_reset.setSizePolicy(sizePolicy)
        self.button_reset.setMinimumSize(QtCore.QSize(100, 25))
        self.button_reset.setMaximumSize(QtCore.QSize(100, 25))
        self.button_reset.setDefault(True)
        self.button_reset.setObjectName(_fromUtf8("button_reset"))
        self.gridLayout_5.addWidget(self.button_reset, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.widget_buttonsReset, 7, 0, 1, 1)
        self.text_reset = QtGui.QTextBrowser(self.tab_reset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_reset.sizePolicy().hasHeightForWidth())
        self.text_reset.setSizePolicy(sizePolicy)
        self.text_reset.setMinimumSize(QtCore.QSize(401, 131))
        self.text_reset.setObjectName(_fromUtf8("text_reset"))
        self.gridLayout_9.addWidget(self.text_reset, 8, 0, 1, 1)
        self.tabWidget.addTab(self.tab_reset, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        GitWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GitWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_search.setCurrentIndex(0)
        self.tabWidget_merge.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GitWindow)
        GitWindow.setTabOrder(self.tabWidget, self.tabWidget)
        GitWindow.setTabOrder(self.tabWidget, self.tabWidget_search)
        GitWindow.setTabOrder(self.tabWidget_search, self.timeEdit_from)
        GitWindow.setTabOrder(self.timeEdit_from, self.timeEdit_to)
        GitWindow.setTabOrder(self.timeEdit_to, self.spinBox_times)
        GitWindow.setTabOrder(self.spinBox_times, self.dateEdit_date)
        GitWindow.setTabOrder(self.dateEdit_date, self.button_get)
        GitWindow.setTabOrder(self.button_get, self.list_commit)
        GitWindow.setTabOrder(self.list_commit, self.box_file)
        GitWindow.setTabOrder(self.box_file, self.list_commit_oneFile)
        GitWindow.setTabOrder(self.list_commit_oneFile, self.button_createCommit)
        GitWindow.setTabOrder(self.button_createCommit, self.button_status)
        GitWindow.setTabOrder(self.button_status, self.text_status)
        GitWindow.setTabOrder(self.text_status, self.button_refreshIgnore)
        GitWindow.setTabOrder(self.button_refreshIgnore, self.lineEdit_addIgnore)
        GitWindow.setTabOrder(self.lineEdit_addIgnore, self.button_addIgnore)
        GitWindow.setTabOrder(self.button_addIgnore, self.list_ignoreList)
        GitWindow.setTabOrder(self.list_ignoreList, self.button_deleteIgnore)
        GitWindow.setTabOrder(self.button_deleteIgnore, self.button_applyIgnore)
        GitWindow.setTabOrder(self.button_applyIgnore, self.tabWidget_merge)
        GitWindow.setTabOrder(self.tabWidget_merge, self.box_old)
        GitWindow.setTabOrder(self.box_old, self.box_new)
        GitWindow.setTabOrder(self.box_new, self.lineEdit_old)
        GitWindow.setTabOrder(self.lineEdit_old, self.button_browseOld)
        GitWindow.setTabOrder(self.button_browseOld, self.lineEdit_new)
        GitWindow.setTabOrder(self.lineEdit_new, self.button_browseNew)
        GitWindow.setTabOrder(self.button_browseNew, self.button_patch)
        GitWindow.setTabOrder(self.button_patch, self.button_applyPatch)
        GitWindow.setTabOrder(self.button_applyPatch, self.lineEdit_id)
        GitWindow.setTabOrder(self.lineEdit_id, self.box_typeReset)
        GitWindow.setTabOrder(self.box_typeReset, self.box_filename)
        GitWindow.setTabOrder(self.box_filename, self.button_refresh)
        GitWindow.setTabOrder(self.button_refresh, self.button_reset)
        GitWindow.setTabOrder(self.button_reset, self.text_reset)
        GitWindow.setTabOrder(self.text_reset, self.button_close)

    def retranslateUi(self, GitWindow):
        GitWindow.setWindowTitle(_translate("GitWindow", "Работа с git", None))
        self.button_close.setText(_translate("GitWindow", "Закрыть", None))
        self.label_timeFrom.setText(_translate("GitWindow", "с", None))
        self.timeEdit_from.setDisplayFormat(_translate("GitWindow", "HH:mm dd.MM.yyyy", None))
        self.label_timeTo.setText(_translate("GitWindow", "по", None))
        self.timeEdit_to.setDisplayFormat(_translate("GitWindow", "H:mm dd.MM.yyyy", None))
        self.label_titleInt.setText(_translate("GitWindow", "В указанный интервал", None))
        self.tabWidget_search.setTabText(self.tabWidget_search.indexOf(self.tab_search_01), _translate("GitWindow", "В интервал", None))
        self.label_times.setText(_translate("GitWindow", "Число коммитов", None))
        self.label_titleTimes.setText(_translate("GitWindow", "По количеству коммитов", None))
        self.tabWidget_search.setTabText(self.tabWidget_search.indexOf(self.tab_search_02), _translate("GitWindow", "По числу коммитов", None))
        self.label_date.setText(_translate("GitWindow", "Дата коммита", None))
        self.dateEdit_date.setDisplayFormat(_translate("GitWindow", "dd.MM.yyyy", None))
        self.label_titleDate.setText(_translate("GitWindow", "По дате коммита", None))
        self.tabWidget_search.setTabText(self.tabWidget_search.indexOf(self.tab_search_03), _translate("GitWindow", "По дате", None))
        self.button_get.setText(_translate("GitWindow", "Вывести", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("GitWindow", "Поиск", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_oneFile), _translate("GitWindow", "Страница", None))
        self.button_createCommit.setText(_translate("GitWindow", "Создать коммит", None))
        self.button_status.setText(_translate("GitWindow", "Показать статус", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_status), _translate("GitWindow", "Статус", None))
        self.button_refreshIgnore.setText(_translate("GitWindow", "Обновить", None))
        self.button_addIgnore.setText(_translate("GitWindow", "Добавить", None))
        self.button_deleteIgnore.setText(_translate("GitWindow", "Удалить строку", None))
        self.button_applyIgnore.setText(_translate("GitWindow", "Применить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ignore), _translate("GitWindow", "Игнор-лист", None))
        self.pushButton_addSubmodule.setText(_translate("GitWindow", "Добавить", None))
        self.pushButton_refreshSubmodules.setText(_translate("GitWindow", "Обновить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_submodules), _translate("GitWindow", "Подмодули", None))
        self.label_merge.setText(_translate("GitWindow", "<html><head/><body><p align=\"center\">Изменения будут применены от <span style=\" font-weight:600; color:#ff0000;\">СТАРОГО</span> файла к <span style=\" font-weight:600; color:#ff0000;\">НОВОМУ</span>.</p><p align=\"center\"><span style=\" font-weight:600; color:#ff0000;\">НОВЫЙ</span> файл будет <span style=\" font-weight:600;\">ПЕРЕЗАПИСАН</span>.</p></body></html>", None))
        self.label_titleSearch.setText(_translate("GitWindow", "Поиск файлов", None))
        self.label_old01.setText(_translate("GitWindow", "Старый файл", None))
        self.label_new01.setText(_translate("GitWindow", "Новый файл", None))
        self.tabWidget_merge.setTabText(self.tabWidget_merge.indexOf(self.tab_merge_01), _translate("GitWindow", "Поиск", None))
        self.label_old02.setText(_translate("GitWindow", "Старый файл", None))
        self.button_browseOld.setText(_translate("GitWindow", "Обзор", None))
        self.label_new02.setText(_translate("GitWindow", "Новый файл", None))
        self.button_browseNew.setText(_translate("GitWindow", "Обзор", None))
        self.label_titleBrowse.setText(_translate("GitWindow", "Указать файл вручную", None))
        self.tabWidget_merge.setTabText(self.tabWidget_merge.indexOf(self.tab_merge_02), _translate("GitWindow", "Указать", None))
        self.button_patch.setText(_translate("GitWindow", "Редактировать патч", None))
        self.button_applyPatch.setText(_translate("GitWindow", "Принять", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_merge), _translate("GitWindow", "Слияние", None))
        self.label_text1.setText(_translate("GitWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\">Внимание!</span></p></body></html>", None))
        self.label_text2.setText(_translate("GitWindow", "Откат изменений может нарушить работу Вашей системы.", None))
        self.label_text3.setText(_translate("GitWindow", "Откат к ранним версиям осуществляйте", None))
        self.label_text4.setText(_translate("GitWindow", "на свой страх и риск.", None))
        self.label_id.setText(_translate("GitWindow", "Идентификатор коммита", None))
        self.label_typeReset.setText(_translate("GitWindow", "Тип отката", None))
        self.box_typeReset.setItemText(0, _translate("GitWindow", "Откат всех файлов", None))
        self.box_typeReset.setItemText(1, _translate("GitWindow", "Откат одного файла", None))
        self.label_filename.setText(_translate("GitWindow", "Выберете файл", None))
        self.button_refresh.setText(_translate("GitWindow", "Обновить список", None))
        self.button_reset.setText(_translate("GitWindow", "Откатить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_reset), _translate("GitWindow", "Откат изменений", None))

