# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingswin.ui'
#
# Created: Mon Feb 18 16:11:08 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName(_fromUtf8("SettingsWindow"))
        SettingsWindow.resize(410, 250)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsWindow.sizePolicy().hasHeightForWidth())
        SettingsWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(SettingsWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(410, 250))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.widget_buttons = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_buttons.sizePolicy().hasHeightForWidth())
        self.widget_buttons.setSizePolicy(sizePolicy)
        self.widget_buttons.setObjectName(_fromUtf8("widget_buttons"))
        self.gridLayout = QtGui.QGridLayout(self.widget_buttons)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.button_default = QtGui.QPushButton(self.widget_buttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_default.sizePolicy().hasHeightForWidth())
        self.button_default.setSizePolicy(sizePolicy)
        self.button_default.setMinimumSize(QtCore.QSize(125, 25))
        self.button_default.setMaximumSize(QtCore.QSize(125, 25))
        self.button_default.setDefault(True)
        self.button_default.setObjectName(_fromUtf8("button_default"))
        self.gridLayout.addWidget(self.button_default, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.button_apply = QtGui.QPushButton(self.widget_buttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_apply.sizePolicy().hasHeightForWidth())
        self.button_apply.setSizePolicy(sizePolicy)
        self.button_apply.setMinimumSize(QtCore.QSize(100, 25))
        self.button_apply.setMaximumSize(QtCore.QSize(25, 100))
        self.button_apply.setDefault(True)
        self.button_apply.setObjectName(_fromUtf8("button_apply"))
        self.gridLayout.addWidget(self.button_apply, 0, 2, 1, 1)
        self.button_close = QtGui.QPushButton(self.widget_buttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setMinimumSize(QtCore.QSize(100, 25))
        self.button_close.setMaximumSize(QtCore.QSize(100, 25))
        self.button_close.setDefault(True)
        self.button_close.setObjectName(_fromUtf8("button_close"))
        self.gridLayout.addWidget(self.button_close, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.widget_buttons, 6, 0, 1, 1)
        self.widget_lang = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_lang.sizePolicy().hasHeightForWidth())
        self.widget_lang.setSizePolicy(sizePolicy)
        self.widget_lang.setObjectName(_fromUtf8("widget_lang"))
        self.formLayout = QtGui.QFormLayout(self.widget_lang)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_lang = QtGui.QLabel(self.widget_lang)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lang.sizePolicy().hasHeightForWidth())
        self.label_lang.setSizePolicy(sizePolicy)
        self.label_lang.setMinimumSize(QtCore.QSize(100, 25))
        self.label_lang.setMaximumSize(QtCore.QSize(100, 25))
        self.label_lang.setObjectName(_fromUtf8("label_lang"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_lang)
        self.box_lang = QtGui.QComboBox(self.widget_lang)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_lang.sizePolicy().hasHeightForWidth())
        self.box_lang.setSizePolicy(sizePolicy)
        self.box_lang.setMinimumSize(QtCore.QSize(275, 25))
        self.box_lang.setMaximumSize(QtCore.QSize(16777215, 25))
        self.box_lang.setObjectName(_fromUtf8("box_lang"))
        self.box_lang.addItem(_fromUtf8(""))
        self.box_lang.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.box_lang)
        self.gridLayout_3.addWidget(self.widget_lang, 0, 0, 1, 1)
        self.widget_browse = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_browse.sizePolicy().hasHeightForWidth())
        self.widget_browse.setSizePolicy(sizePolicy)
        self.widget_browse.setObjectName(_fromUtf8("widget_browse"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_browse)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.button_browse = QtGui.QPushButton(self.widget_browse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse.sizePolicy().hasHeightForWidth())
        self.button_browse.setSizePolicy(sizePolicy)
        self.button_browse.setMinimumSize(QtCore.QSize(100, 25))
        self.button_browse.setMaximumSize(QtCore.QSize(100, 25))
        self.button_browse.setDefault(True)
        self.button_browse.setObjectName(_fromUtf8("button_browse"))
        self.gridLayout_2.addWidget(self.button_browse, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_browse, 3, 0, 1, 1)
        self.widget_service = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_service.sizePolicy().hasHeightForWidth())
        self.widget_service.setSizePolicy(sizePolicy)
        self.widget_service.setObjectName(_fromUtf8("widget_service"))
        self.formLayout_2 = QtGui.QFormLayout(self.widget_service)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_service = QtGui.QLabel(self.widget_service)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_service.sizePolicy().hasHeightForWidth())
        self.label_service.setSizePolicy(sizePolicy)
        self.label_service.setMinimumSize(QtCore.QSize(100, 25))
        self.label_service.setMaximumSize(QtCore.QSize(100, 25))
        self.label_service.setObjectName(_fromUtf8("label_service"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_service)
        self.lineEdit_service = QtGui.QLineEdit(self.widget_service)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_service.sizePolicy().hasHeightForWidth())
        self.lineEdit_service.setSizePolicy(sizePolicy)
        self.lineEdit_service.setMinimumSize(QtCore.QSize(275, 25))
        self.lineEdit_service.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_service.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_service.setObjectName(_fromUtf8("lineEdit_service"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_service)
        self.gridLayout_3.addWidget(self.widget_service, 1, 0, 1, 1)
        self.widget_editor = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_editor.sizePolicy().hasHeightForWidth())
        self.widget_editor.setSizePolicy(sizePolicy)
        self.widget_editor.setObjectName(_fromUtf8("widget_editor"))
        self.formLayout_5 = QtGui.QFormLayout(self.widget_editor)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_editor = QtGui.QLabel(self.widget_editor)
        self.label_editor.setMinimumSize(QtCore.QSize(140, 25))
        self.label_editor.setMaximumSize(QtCore.QSize(140, 25))
        self.label_editor.setObjectName(_fromUtf8("label_editor"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_editor)
        self.lineEdit_editor = QtGui.QLineEdit(self.widget_editor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_editor.sizePolicy().hasHeightForWidth())
        self.lineEdit_editor.setSizePolicy(sizePolicy)
        self.lineEdit_editor.setMinimumSize(QtCore.QSize(250, 25))
        self.lineEdit_editor.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_editor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_editor.setObjectName(_fromUtf8("lineEdit_editor"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_editor)
        self.gridLayout_3.addWidget(self.widget_editor, 5, 0, 1, 1)
        self.widget_config = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_config.sizePolicy().hasHeightForWidth())
        self.widget_config.setSizePolicy(sizePolicy)
        self.widget_config.setObjectName(_fromUtf8("widget_config"))
        self.formLayout_6 = QtGui.QFormLayout(self.widget_config)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_config = QtGui.QLabel(self.widget_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_config.sizePolicy().hasHeightForWidth())
        self.label_config.setSizePolicy(sizePolicy)
        self.label_config.setMinimumSize(QtCore.QSize(125, 25))
        self.label_config.setMaximumSize(QtCore.QSize(125, 25))
        self.label_config.setObjectName(_fromUtf8("label_config"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_config)
        self.lineEdit_config = QtGui.QLineEdit(self.widget_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_config.sizePolicy().hasHeightForWidth())
        self.lineEdit_config.setSizePolicy(sizePolicy)
        self.lineEdit_config.setMinimumSize(QtCore.QSize(170, 25))
        self.lineEdit_config.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_config.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_config.setObjectName(_fromUtf8("lineEdit_config"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_config)
        self.gridLayout_3.addWidget(self.widget_config, 2, 0, 1, 1)
        self.widget_system = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_system.sizePolicy().hasHeightForWidth())
        self.widget_system.setSizePolicy(sizePolicy)
        self.widget_system.setObjectName(_fromUtf8("widget_system"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_system)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_system = QtGui.QLabel(self.widget_system)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_system.sizePolicy().hasHeightForWidth())
        self.label_system.setSizePolicy(sizePolicy)
        self.label_system.setMinimumSize(QtCore.QSize(141, 25))
        self.label_system.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_system.setObjectName(_fromUtf8("label_system"))
        self.gridLayout_4.addWidget(self.label_system, 0, 0, 1, 1)
        self.checkBox_sudo = QtGui.QCheckBox(self.widget_system)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_sudo.sizePolicy().hasHeightForWidth())
        self.checkBox_sudo.setSizePolicy(sizePolicy)
        self.checkBox_sudo.setMinimumSize(QtCore.QSize(160, 25))
        self.checkBox_sudo.setMaximumSize(QtCore.QSize(160, 25))
        self.checkBox_sudo.setChecked(True)
        self.checkBox_sudo.setObjectName(_fromUtf8("checkBox_sudo"))
        self.gridLayout_4.addWidget(self.checkBox_sudo, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_system, 4, 0, 1, 1)
        SettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)
        SettingsWindow.setTabOrder(self.box_lang, self.lineEdit_service)
        SettingsWindow.setTabOrder(self.lineEdit_service, self.lineEdit_config)
        SettingsWindow.setTabOrder(self.lineEdit_config, self.button_browse)
        SettingsWindow.setTabOrder(self.button_browse, self.checkBox_sudo)
        SettingsWindow.setTabOrder(self.checkBox_sudo, self.lineEdit_editor)
        SettingsWindow.setTabOrder(self.lineEdit_editor, self.button_default)
        SettingsWindow.setTabOrder(self.button_default, self.button_apply)
        SettingsWindow.setTabOrder(self.button_apply, self.button_close)

    def retranslateUi(self, SettingsWindow):
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Настройки", None))
        self.button_default.setText(_translate("SettingsWindow", "По умолчанию", None))
        self.button_apply.setText(_translate("SettingsWindow", "Применить", None))
        self.button_close.setText(_translate("SettingsWindow", "Закрыть", None))
        self.label_lang.setText(_translate("SettingsWindow", "Язык", None))
        self.box_lang.setItemText(0, _translate("SettingsWindow", "English", None))
        self.box_lang.setItemText(1, _translate("SettingsWindow", "Русский", None))
        self.button_browse.setText(_translate("SettingsWindow", "Обзор", None))
        self.label_service.setText(_translate("SettingsWindow", "Service", None))
        self.label_editor.setText(_translate("SettingsWindow", "Текстовый редактор", None))
        self.label_config.setText(_translate("SettingsWindow", "Настройки git-etc", None))
        self.label_system.setText(_translate("SettingsWindow", "Системные настройки", None))
        self.checkBox_sudo.setText(_translate("SettingsWindow", "Использовать sudo", None))

