.TH GIT-ETC.CONF 5
.SH NAME
git-etc.conf - git-etc configuration file
.SH SYNOPSIS
/etc/conf.d/git-etc.conf
.SH DESCRIPTION
This file configures various parameters of 
.BR git-etc (1).
.SH OPTIONS
.TP
.I DIRECTORY=
Full path to working directory with observed files.
.TP
.I TIMESLEEP=
Time interval between updates.
.TP
.I IGNORELIST=
List of files that will not be observed. Separator is ";;". May be empty.
.SH SEE ALSO
.BR git-etc (1)
