.TH git-etc 1  "April 15, 2012" "version 2.1.2" "USER COMMANDS"
.SH NAME
git-etc - simple daemon
.SH SYNOPSIS
.B git-etc
[--for-all] [-i ignore-list] [-h|--help] [-v|--version] -d /path/to/directory -t time-to-sleep
.SH DESCRIPTION
.B git-etc
is a simple daemon written on BASH that automatically creates git repository in the given directory and creates commit at the specified time interval.
.SH OPTIONS
.TP
-d | --directory /path/to/directory
Full path to working directory with observed files.
.TP
-t | --timesleep time-to-sleep
Time interval between updates. It must be integer and >=1.
.TP
--for-all
Do not change rights to .git during creation repository.
.TP
ignore-list
List of files that will not be observed. Separator is ";;".
.TP
-h | --help
Show help and exit.
.TP
-v | --version
Show version and exit.
.SH FILES
.TP
/usr/lib/systemd/system/git-etc.service
Systemd service file.
.TP
/etc/conf.d/git-etc.conf
Configuration file.
.SH EXAMPLES
.TP
# git-etc -d /etc -t 12 -i mtab;;*[bB]ak;;*pacnew
Start daemon in directory
.B /etc
with time interval between updates of 
.B 12 
hours. Files 
.B mtab, *bak, *Bak and *pacnew 
will be ignored.
.TP
# systemctl start git-etc.service
Start daemon with parameters that are described in configuration file.
.TP
# systemctl enable git-etc.service
Enable daemon autostart.
.SH USAGE WITH SYSTEMD
If you need change path to configuration file or change parameters, copy standart service file to /etc directory:
.PP
.nf
# cp /usr/lib/systemd/system/git-etc.service /etc/systemd/system/git-etc-my-profile.service
.fi
.PP
Then replace path to configuration file to your option. For example,
.PP
.B from:
.nf
EnvironmentFile=/etc/conf.d/git-etc.conf
.fi
.B to
.nf
EnvironmentFile=/etc/conf.d/git-etc-my-profile.conf
.fi
.PP
Copy configuration file and edit it:
.PP
.nf
# cp /etc/conf.d/git-etc.conf /etc/conf.d/git-etc-my-profile.conf
.fi
.PP
Then start service:
.PP
.nf
# systemctl start git-etc-my-profile.service
.fi
.SH ERRORS
Use
.B journalctl
to determine errors:
.nf
  [II] - information string
  [WW] - warning
  [EE] - error
.fi
.SH SEE ALSO
.BR git-etc.conf (5)
.BR ctrlconf (1)
.SH AUTHOR
Evgeniy Alexeev aka arcanis <\fIesalexeev@gmail.com\fR>
