# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configwin.ui'
#
# Created: Mon Feb 18 02:19:01 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ConfigureWindow(object):
    def setupUi(self, ConfigureWindow):
        ConfigureWindow.setObjectName(_fromUtf8("ConfigureWindow"))
        ConfigureWindow.resize(430, 149)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConfigureWindow.sizePolicy().hasHeightForWidth())
        ConfigureWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(ConfigureWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 150))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_directory = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_directory.sizePolicy().hasHeightForWidth())
        self.label_directory.setSizePolicy(sizePolicy)
        self.label_directory.setMinimumSize(QtCore.QSize(150, 25))
        self.label_directory.setMaximumSize(QtCore.QSize(150, 25))
        self.label_directory.setObjectName(_fromUtf8("label_directory"))
        self.gridLayout.addWidget(self.label_directory, 0, 0, 1, 1)
        self.button_refresh = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_refresh.sizePolicy().hasHeightForWidth())
        self.button_refresh.setSizePolicy(sizePolicy)
        self.button_refresh.setMinimumSize(QtCore.QSize(100, 25))
        self.button_refresh.setMaximumSize(QtCore.QSize(100, 25))
        self.button_refresh.setDefault(True)
        self.button_refresh.setObjectName(_fromUtf8("button_refresh"))
        self.gridLayout.addWidget(self.button_refresh, 4, 0, 1, 1)
        self.lineEdit_directory = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_directory.sizePolicy().hasHeightForWidth())
        self.lineEdit_directory.setSizePolicy(sizePolicy)
        self.lineEdit_directory.setMinimumSize(QtCore.QSize(100, 25))
        self.lineEdit_directory.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_directory.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_directory.setObjectName(_fromUtf8("lineEdit_directory"))
        self.gridLayout.addWidget(self.lineEdit_directory, 0, 1, 1, 4)
        self.button_close = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setMinimumSize(QtCore.QSize(100, 25))
        self.button_close.setMaximumSize(QtCore.QSize(100, 25))
        self.button_close.setDefault(True)
        self.button_close.setObjectName(_fromUtf8("button_close"))
        self.gridLayout.addWidget(self.button_close, 4, 4, 1, 1)
        self.lineEdit_ignoreList = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ignoreList.sizePolicy().hasHeightForWidth())
        self.lineEdit_ignoreList.setSizePolicy(sizePolicy)
        self.lineEdit_ignoreList.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit_ignoreList.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lineEdit_ignoreList.setObjectName(_fromUtf8("lineEdit_ignoreList"))
        self.gridLayout.addWidget(self.lineEdit_ignoreList, 3, 0, 1, 5)
        self.button_apply = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_apply.sizePolicy().hasHeightForWidth())
        self.button_apply.setSizePolicy(sizePolicy)
        self.button_apply.setMinimumSize(QtCore.QSize(100, 25))
        self.button_apply.setMaximumSize(QtCore.QSize(100, 25))
        self.button_apply.setDefault(True)
        self.button_apply.setObjectName(_fromUtf8("button_apply"))
        self.gridLayout.addWidget(self.button_apply, 4, 3, 1, 1)
        self.label_timeSleep = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timeSleep.sizePolicy().hasHeightForWidth())
        self.label_timeSleep.setSizePolicy(sizePolicy)
        self.label_timeSleep.setMinimumSize(QtCore.QSize(170, 25))
        self.label_timeSleep.setMaximumSize(QtCore.QSize(170, 25))
        self.label_timeSleep.setObjectName(_fromUtf8("label_timeSleep"))
        self.gridLayout.addWidget(self.label_timeSleep, 1, 0, 1, 2)
        self.lineEdit_timeSleep = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_timeSleep.sizePolicy().hasHeightForWidth())
        self.lineEdit_timeSleep.setSizePolicy(sizePolicy)
        self.lineEdit_timeSleep.setMinimumSize(QtCore.QSize(100, 25))
        self.lineEdit_timeSleep.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_timeSleep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_timeSleep.setObjectName(_fromUtf8("lineEdit_timeSleep"))
        self.gridLayout.addWidget(self.lineEdit_timeSleep, 1, 2, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.label_ignoreList = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ignoreList.sizePolicy().hasHeightForWidth())
        self.label_ignoreList.setSizePolicy(sizePolicy)
        self.label_ignoreList.setMinimumSize(QtCore.QSize(300, 25))
        self.label_ignoreList.setMaximumSize(QtCore.QSize(300, 25))
        self.label_ignoreList.setObjectName(_fromUtf8("label_ignoreList"))
        self.gridLayout.addWidget(self.label_ignoreList, 2, 0, 1, 4)
        ConfigureWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConfigureWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfigureWindow)
        ConfigureWindow.setTabOrder(self.lineEdit_directory, self.lineEdit_timeSleep)
        ConfigureWindow.setTabOrder(self.lineEdit_timeSleep, self.lineEdit_ignoreList)
        ConfigureWindow.setTabOrder(self.lineEdit_ignoreList, self.button_refresh)
        ConfigureWindow.setTabOrder(self.button_refresh, self.button_apply)
        ConfigureWindow.setTabOrder(self.button_apply, self.button_close)

    def retranslateUi(self, ConfigureWindow):
        ConfigureWindow.setWindowTitle(_translate("ConfigureWindow", "Настроить сервис", None))
        self.label_directory.setText(_translate("ConfigureWindow", "Рабочая директория:", None))
        self.button_refresh.setText(_translate("ConfigureWindow", "Обновить", None))
        self.button_close.setText(_translate("ConfigureWindow", "Закрыть", None))
        self.button_apply.setText(_translate("ConfigureWindow", "Применить", None))
        self.label_timeSleep.setText(_translate("ConfigureWindow", "Интервал обновления, ч:", None))
        self.label_ignoreList.setText(_translate("ConfigureWindow", "Список игнорируемых файлов:", None))

