#!/bin/bash

case "$1" in
  -h | --help ) echo -e "Simple daemon for monitoring changes in files";\
    echo -e "\nUsage: git-etc [ -h | --help ] [ -v | --version ] /path/to/directory time-to-sleep [ ignore-list ]";\
    echo -e "\n  -v  --version - show version and exit";\
    echo -e "  -h  --help    - show this help and exit";\
    echo -e "\nSee \"man 1 git-etc\" for more details";\
    exit 1;;
  -v | --version ) echo -e "                   git-etc                   ";\
    echo -e "Simple daemon for monitoring changes in files";\
    echo -e "Version : 1.0a                  License : GPL";\
    echo -e "Author :          Evgeniy Alexeev aka arcanis";\
    echo -e "E-mail :             esalexeev (at) gmail.com";\
    exit 1;;
esac


isnum () {
    (t=$(( 0$1+0 ))) 2>/dev/null
}


if [[ -z "$1" || -z "$2" ]]; then
  echo "[EE]: Parametrs aren't set"
  exit 1
else
  DIRECTORY=$1
  TIMESLEEP=$2
fi

if [[ -z "$3" ]]; then
  IGNORELIST=NULL
else
  IGNORELIST=`echo $3 | sed -e 's/;;/ /g'`
fi

if [ ! -d "$DIRECTORY" ]; then
  echo "[EE]: Directory '$DIRECTORY' doesn't exist"
  exit 1
fi

if isnum $TIMESLEEP; then
  if [ $TIMESLEEP -ge 1 ]; then
    echo "[II]: Set DIRECTORY to '$DIRECTORY'"
    TIMESLEEP=$(( $TIMESLEEP*3600 ))
    echo "[II]: Set TIMESLEEP to '$TIMESLEEP' sec"
  else
    echo "[EE]: '$TIMESLEEP' isn't valid number"
    exit 1
  fi
else
  echo "[EE]: '$TIMESLEEP' isn't a number"
  exit 1
fi


# Change cwd
cd /

# Output to /dev/null
< /dev/null > /dev/null 2>&1 &


# Creating git repository
GITDIR=$DIRECTORY/.git
if [ ! -d "$GITDIR" ]; then
  echo "[II]: Creating git repository"
  cd $DIRECTORY
  git init
  cd /
  echo "[II]: Changing rights to '$GITDIR'"
  chmod -R o-rwx $GITDIR
  if [[ $IGNORELIST != NULL ]]; then
    echo "[II]: Adding files in ingore-list"
    for IGNORE in $( echo $IGNORELIST ); do
      echo $IGNORE >> $GITDIR/info/exclude
    done
  else
    echo "[WW]: IGNORELIST isn't set"
  fi
fi


# Forking
(
  while true; do
# Creating commit
    cd $DIRECTORY
    echo "[II]: Adding files" 
    git add -A .
    echo "[II]: Creating new commit"
    git commit -m `date +%Y%m%d%H%M%S-%N`
    cd /

# Waiting $TIMESLEEP hours
    echo "[II]: Waiting '$TIMESLEEP' sec"
    exit 1
    sleep $TIMESLEEP
  done
) &
