# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gitwin.ui'
#
# Created: Fri Feb 15 19:34:39 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GitWindow(object):
    def setupUi(self, GitWindow):
        GitWindow.setObjectName(_fromUtf8("GitWindow"))
        GitWindow.resize(431, 409)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GitWindow.sizePolicy().hasHeightForWidth())
        GitWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(GitWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_mode = QtGui.QLabel(self.centralwidget)
        self.label_mode.setGeometry(QtCore.QRect(10, 10, 161, 21))
        self.label_mode.setObjectName(_fromUtf8("label_mode"))
        self.box_mode = QtGui.QComboBox(self.centralwidget)
        self.box_mode.setGeometry(QtCore.QRect(180, 10, 241, 24))
        self.box_mode.setObjectName(_fromUtf8("box_mode"))
        self.box_mode.addItem(_fromUtf8(""))
        self.box_mode.addItem(_fromUtf8(""))
        self.box_mode.addItem(_fromUtf8(""))
        self.timeEdit_from = QtGui.QDateTimeEdit(self.centralwidget)
        self.timeEdit_from.setEnabled(True)
        self.timeEdit_from.setGeometry(QtCore.QRect(60, 40, 141, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_from.sizePolicy().hasHeightForWidth())
        self.timeEdit_from.setSizePolicy(sizePolicy)
        self.timeEdit_from.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_from.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_from.setCalendarPopup(True)
        self.timeEdit_from.setObjectName(_fromUtf8("timeEdit_from"))
        self.label_timeFrom = QtGui.QLabel(self.centralwidget)
        self.label_timeFrom.setEnabled(True)
        self.label_timeFrom.setGeometry(QtCore.QRect(30, 40, 31, 21))
        self.label_timeFrom.setObjectName(_fromUtf8("label_timeFrom"))
        self.timeEdit_to = QtGui.QDateTimeEdit(self.centralwidget)
        self.timeEdit_to.setEnabled(True)
        self.timeEdit_to.setGeometry(QtCore.QRect(260, 40, 141, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_to.sizePolicy().hasHeightForWidth())
        self.timeEdit_to.setSizePolicy(sizePolicy)
        self.timeEdit_to.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_to.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_to.setCalendarPopup(True)
        self.timeEdit_to.setObjectName(_fromUtf8("timeEdit_to"))
        self.label_timeTo = QtGui.QLabel(self.centralwidget)
        self.label_timeTo.setEnabled(True)
        self.label_timeTo.setGeometry(QtCore.QRect(230, 40, 31, 21))
        self.label_timeTo.setObjectName(_fromUtf8("label_timeTo"))
        self.spinBox_times = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_times.setGeometry(QtCore.QRect(260, 40, 111, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_times.sizePolicy().hasHeightForWidth())
        self.spinBox_times.setSizePolicy(sizePolicy)
        self.spinBox_times.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_times.setMinimum(1)
        self.spinBox_times.setMaximum(999)
        self.spinBox_times.setObjectName(_fromUtf8("spinBox_times"))
        self.label_times = QtGui.QLabel(self.centralwidget)
        self.label_times.setGeometry(QtCore.QRect(60, 40, 121, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_times.sizePolicy().hasHeightForWidth())
        self.label_times.setSizePolicy(sizePolicy)
        self.label_times.setObjectName(_fromUtf8("label_times"))
        self.label_date = QtGui.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(90, 40, 121, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date.sizePolicy().hasHeightForWidth())
        self.label_date.setSizePolicy(sizePolicy)
        self.label_date.setObjectName(_fromUtf8("label_date"))
        self.button_get = QtGui.QPushButton(self.centralwidget)
        self.button_get.setGeometry(QtCore.QRect(300, 70, 101, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get.sizePolicy().hasHeightForWidth())
        self.button_get.setSizePolicy(sizePolicy)
        self.button_get.setDefault(True)
        self.button_get.setObjectName(_fromUtf8("button_get"))
        self.list_commit = QtGui.QListWidget(self.centralwidget)
        self.list_commit.setGeometry(QtCore.QRect(10, 100, 411, 181))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_commit.sizePolicy().hasHeightForWidth())
        self.list_commit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.list_commit.setFont(font)
        self.list_commit.setObjectName(_fromUtf8("list_commit"))
        self.dateEdit_date = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit_date.setGeometry(QtCore.QRect(220, 40, 110, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_date.sizePolicy().hasHeightForWidth())
        self.dateEdit_date.setSizePolicy(sizePolicy)
        self.dateEdit_date.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_date.setDate(QtCore.QDate(2013, 1, 1))
        self.dateEdit_date.setCalendarPopup(True)
        self.dateEdit_date.setObjectName(_fromUtf8("dateEdit_date"))
        GitWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GitWindow)
        QtCore.QMetaObject.connectSlotsByName(GitWindow)
        GitWindow.setTabOrder(self.box_mode, self.timeEdit_from)
        GitWindow.setTabOrder(self.timeEdit_from, self.timeEdit_to)
        GitWindow.setTabOrder(self.timeEdit_to, self.spinBox_times)
        GitWindow.setTabOrder(self.spinBox_times, self.dateEdit_date)
        GitWindow.setTabOrder(self.dateEdit_date, self.button_get)
        GitWindow.setTabOrder(self.button_get, self.list_commit)

    def retranslateUi(self, GitWindow):
        GitWindow.setWindowTitle(_translate("GitWindow", "Работа с git", None))
        self.label_mode.setText(_translate("GitWindow", "Показать коммиты", None))
        self.box_mode.setItemText(0, _translate("GitWindow", "По дате", None))
        self.box_mode.setItemText(1, _translate("GitWindow", "По количеству", None))
        self.box_mode.setItemText(2, _translate("GitWindow", "В определенный день", None))
        self.timeEdit_from.setDisplayFormat(_translate("GitWindow", "HH:mm dd.MM.yyyy", None))
        self.label_timeFrom.setText(_translate("GitWindow", "с", None))
        self.timeEdit_to.setDisplayFormat(_translate("GitWindow", "H:mm dd.MM.yyyy", None))
        self.label_timeTo.setText(_translate("GitWindow", "по", None))
        self.label_times.setText(_translate("GitWindow", "Число коммитов", None))
        self.label_date.setText(_translate("GitWindow", "Дата коммита", None))
        self.button_get.setText(_translate("GitWindow", "Вывести", None))
        self.dateEdit_date.setDisplayFormat(_translate("GitWindow", "dd.MM.yyyy", None))

