# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gitwin.ui'
#
# Created: Sun Feb 17 17:07:44 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GitWindow(object):
    def setupUi(self, GitWindow):
        GitWindow.setObjectName(_fromUtf8("GitWindow"))
        GitWindow.resize(433, 430)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GitWindow.sizePolicy().hasHeightForWidth())
        GitWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(GitWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 411, 381))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_search = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_search.sizePolicy().hasHeightForWidth())
        self.tab_search.setSizePolicy(sizePolicy)
        self.tab_search.setObjectName(_fromUtf8("tab_search"))
        self.box_mode = QtGui.QComboBox(self.tab_search)
        self.box_mode.setGeometry(QtCore.QRect(160, 10, 231, 24))
        self.box_mode.setObjectName(_fromUtf8("box_mode"))
        self.box_mode.addItem(_fromUtf8(""))
        self.box_mode.addItem(_fromUtf8(""))
        self.box_mode.addItem(_fromUtf8(""))
        self.label_mode = QtGui.QLabel(self.tab_search)
        self.label_mode.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.label_mode.setObjectName(_fromUtf8("label_mode"))
        self.label_timeFrom = QtGui.QLabel(self.tab_search)
        self.label_timeFrom.setEnabled(True)
        self.label_timeFrom.setGeometry(QtCore.QRect(10, 40, 31, 21))
        self.label_timeFrom.setObjectName(_fromUtf8("label_timeFrom"))
        self.timeEdit_from = QtGui.QDateTimeEdit(self.tab_search)
        self.timeEdit_from.setEnabled(True)
        self.timeEdit_from.setGeometry(QtCore.QRect(50, 40, 141, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_from.sizePolicy().hasHeightForWidth())
        self.timeEdit_from.setSizePolicy(sizePolicy)
        self.timeEdit_from.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_from.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_from.setCalendarPopup(True)
        self.timeEdit_from.setObjectName(_fromUtf8("timeEdit_from"))
        self.timeEdit_to = QtGui.QDateTimeEdit(self.tab_search)
        self.timeEdit_to.setEnabled(True)
        self.timeEdit_to.setGeometry(QtCore.QRect(250, 40, 141, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_to.sizePolicy().hasHeightForWidth())
        self.timeEdit_to.setSizePolicy(sizePolicy)
        self.timeEdit_to.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_to.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_to.setCalendarPopup(True)
        self.timeEdit_to.setObjectName(_fromUtf8("timeEdit_to"))
        self.label_timeTo = QtGui.QLabel(self.tab_search)
        self.label_timeTo.setEnabled(True)
        self.label_timeTo.setGeometry(QtCore.QRect(210, 40, 31, 21))
        self.label_timeTo.setObjectName(_fromUtf8("label_timeTo"))
        self.label_times = QtGui.QLabel(self.tab_search)
        self.label_times.setGeometry(QtCore.QRect(60, 40, 121, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_times.sizePolicy().hasHeightForWidth())
        self.label_times.setSizePolicy(sizePolicy)
        self.label_times.setObjectName(_fromUtf8("label_times"))
        self.spinBox_times = QtGui.QSpinBox(self.tab_search)
        self.spinBox_times.setGeometry(QtCore.QRect(230, 40, 111, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_times.sizePolicy().hasHeightForWidth())
        self.spinBox_times.setSizePolicy(sizePolicy)
        self.spinBox_times.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_times.setMinimum(1)
        self.spinBox_times.setMaximum(999)
        self.spinBox_times.setObjectName(_fromUtf8("spinBox_times"))
        self.dateEdit_date = QtGui.QDateEdit(self.tab_search)
        self.dateEdit_date.setGeometry(QtCore.QRect(230, 40, 110, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_date.sizePolicy().hasHeightForWidth())
        self.dateEdit_date.setSizePolicy(sizePolicy)
        self.dateEdit_date.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_date.setDate(QtCore.QDate(2013, 1, 1))
        self.dateEdit_date.setCalendarPopup(True)
        self.dateEdit_date.setObjectName(_fromUtf8("dateEdit_date"))
        self.label_date = QtGui.QLabel(self.tab_search)
        self.label_date.setGeometry(QtCore.QRect(60, 40, 121, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date.sizePolicy().hasHeightForWidth())
        self.label_date.setSizePolicy(sizePolicy)
        self.label_date.setObjectName(_fromUtf8("label_date"))
        self.button_get = QtGui.QPushButton(self.tab_search)
        self.button_get.setGeometry(QtCore.QRect(280, 70, 101, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get.sizePolicy().hasHeightForWidth())
        self.button_get.setSizePolicy(sizePolicy)
        self.button_get.setDefault(True)
        self.button_get.setObjectName(_fromUtf8("button_get"))
        self.list_commit = QtGui.QListWidget(self.tab_search)
        self.list_commit.setGeometry(QtCore.QRect(0, 100, 401, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_commit.sizePolicy().hasHeightForWidth())
        self.list_commit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.list_commit.setFont(font)
        self.list_commit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.list_commit.setObjectName(_fromUtf8("list_commit"))
        self.tabWidget.addTab(self.tab_search, _fromUtf8(""))
        self.tab_status = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_status.sizePolicy().hasHeightForWidth())
        self.tab_status.setSizePolicy(sizePolicy)
        self.tab_status.setObjectName(_fromUtf8("tab_status"))
        self.button_status = QtGui.QPushButton(self.tab_status)
        self.button_status.setGeometry(QtCore.QRect(270, 10, 121, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_status.sizePolicy().hasHeightForWidth())
        self.button_status.setSizePolicy(sizePolicy)
        self.button_status.setDefault(True)
        self.button_status.setObjectName(_fromUtf8("button_status"))
        self.text_status = QtGui.QTextBrowser(self.tab_status)
        self.text_status.setGeometry(QtCore.QRect(0, 40, 401, 311))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_status.sizePolicy().hasHeightForWidth())
        self.text_status.setSizePolicy(sizePolicy)
        self.text_status.setObjectName(_fromUtf8("text_status"))
        self.button_createCommit = QtGui.QPushButton(self.tab_status)
        self.button_createCommit.setGeometry(QtCore.QRect(10, 10, 121, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_createCommit.sizePolicy().hasHeightForWidth())
        self.button_createCommit.setSizePolicy(sizePolicy)
        self.button_createCommit.setDefault(True)
        self.button_createCommit.setObjectName(_fromUtf8("button_createCommit"))
        self.tabWidget.addTab(self.tab_status, _fromUtf8(""))
        self.tab_merge = QtGui.QWidget()
        self.tab_merge.setObjectName(_fromUtf8("tab_merge"))
        self.button_patch = QtGui.QPushButton(self.tab_merge)
        self.button_patch.setGeometry(QtCore.QRect(250, 140, 141, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_patch.sizePolicy().hasHeightForWidth())
        self.button_patch.setSizePolicy(sizePolicy)
        self.button_patch.setDefault(True)
        self.button_patch.setObjectName(_fromUtf8("button_patch"))
        self.label_old = QtGui.QLabel(self.tab_merge)
        self.label_old.setGeometry(QtCore.QRect(10, 80, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_old.sizePolicy().hasHeightForWidth())
        self.label_old.setSizePolicy(sizePolicy)
        self.label_old.setObjectName(_fromUtf8("label_old"))
        self.box_old = QtGui.QComboBox(self.tab_merge)
        self.box_old.setGeometry(QtCore.QRect(130, 80, 261, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_old.sizePolicy().hasHeightForWidth())
        self.box_old.setSizePolicy(sizePolicy)
        self.box_old.setObjectName(_fromUtf8("box_old"))
        self.box_new = QtGui.QComboBox(self.tab_merge)
        self.box_new.setGeometry(QtCore.QRect(130, 105, 261, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_new.sizePolicy().hasHeightForWidth())
        self.box_new.setSizePolicy(sizePolicy)
        self.box_new.setObjectName(_fromUtf8("box_new"))
        self.label_new = QtGui.QLabel(self.tab_merge)
        self.label_new.setGeometry(QtCore.QRect(10, 105, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_new.sizePolicy().hasHeightForWidth())
        self.label_new.setSizePolicy(sizePolicy)
        self.label_new.setObjectName(_fromUtf8("label_new"))
        self.box_merge = QtGui.QComboBox(self.tab_merge)
        self.box_merge.setGeometry(QtCore.QRect(130, 10, 261, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_merge.sizePolicy().hasHeightForWidth())
        self.box_merge.setSizePolicy(sizePolicy)
        self.box_merge.setObjectName(_fromUtf8("box_merge"))
        self.box_merge.addItem(_fromUtf8(""))
        self.box_merge.addItem(_fromUtf8(""))
        self.label_merge = QtGui.QLabel(self.tab_merge)
        self.label_merge.setGeometry(QtCore.QRect(10, 10, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_merge.sizePolicy().hasHeightForWidth())
        self.label_merge.setSizePolicy(sizePolicy)
        self.label_merge.setObjectName(_fromUtf8("label_merge"))
        self.lineEdit_old = QtGui.QLineEdit(self.tab_merge)
        self.lineEdit_old.setGeometry(QtCore.QRect(130, 80, 171, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_old.sizePolicy().hasHeightForWidth())
        self.lineEdit_old.setSizePolicy(sizePolicy)
        self.lineEdit_old.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_old.setObjectName(_fromUtf8("lineEdit_old"))
        self.button_browseOld = QtGui.QPushButton(self.tab_merge)
        self.button_browseOld.setGeometry(QtCore.QRect(310, 80, 81, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browseOld.sizePolicy().hasHeightForWidth())
        self.button_browseOld.setSizePolicy(sizePolicy)
        self.button_browseOld.setDefault(True)
        self.button_browseOld.setObjectName(_fromUtf8("button_browseOld"))
        self.lineEdit_new = QtGui.QLineEdit(self.tab_merge)
        self.lineEdit_new.setGeometry(QtCore.QRect(130, 105, 171, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_new.sizePolicy().hasHeightForWidth())
        self.lineEdit_new.setSizePolicy(sizePolicy)
        self.lineEdit_new.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_new.setObjectName(_fromUtf8("lineEdit_new"))
        self.button_browseNew = QtGui.QPushButton(self.tab_merge)
        self.button_browseNew.setGeometry(QtCore.QRect(310, 105, 81, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browseNew.sizePolicy().hasHeightForWidth())
        self.button_browseNew.setSizePolicy(sizePolicy)
        self.button_browseNew.setDefault(True)
        self.button_browseNew.setObjectName(_fromUtf8("button_browseNew"))
        self.button_applyPatch = QtGui.QPushButton(self.tab_merge)
        self.button_applyPatch.setGeometry(QtCore.QRect(290, 170, 101, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_applyPatch.sizePolicy().hasHeightForWidth())
        self.button_applyPatch.setSizePolicy(sizePolicy)
        self.button_applyPatch.setDefault(True)
        self.button_applyPatch.setObjectName(_fromUtf8("button_applyPatch"))
        self.tabWidget.addTab(self.tab_merge, _fromUtf8(""))
        self.tab_reset = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_reset.sizePolicy().hasHeightForWidth())
        self.tab_reset.setSizePolicy(sizePolicy)
        self.tab_reset.setObjectName(_fromUtf8("tab_reset"))
        self.label_text1 = QtGui.QLabel(self.tab_reset)
        self.label_text1.setGeometry(QtCore.QRect(10, 10, 381, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text1.sizePolicy().hasHeightForWidth())
        self.label_text1.setSizePolicy(sizePolicy)
        self.label_text1.setObjectName(_fromUtf8("label_text1"))
        self.label_text2 = QtGui.QLabel(self.tab_reset)
        self.label_text2.setGeometry(QtCore.QRect(10, 30, 381, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text2.sizePolicy().hasHeightForWidth())
        self.label_text2.setSizePolicy(sizePolicy)
        self.label_text2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text2.setObjectName(_fromUtf8("label_text2"))
        self.label_text3 = QtGui.QLabel(self.tab_reset)
        self.label_text3.setGeometry(QtCore.QRect(10, 50, 381, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text3.sizePolicy().hasHeightForWidth())
        self.label_text3.setSizePolicy(sizePolicy)
        self.label_text3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text3.setObjectName(_fromUtf8("label_text3"))
        self.label_text4 = QtGui.QLabel(self.tab_reset)
        self.label_text4.setGeometry(QtCore.QRect(10, 70, 381, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text4.sizePolicy().hasHeightForWidth())
        self.label_text4.setSizePolicy(sizePolicy)
        self.label_text4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text4.setObjectName(_fromUtf8("label_text4"))
        self.label_id = QtGui.QLabel(self.tab_reset)
        self.label_id.setGeometry(QtCore.QRect(10, 100, 161, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_id.sizePolicy().hasHeightForWidth())
        self.label_id.setSizePolicy(sizePolicy)
        self.label_id.setObjectName(_fromUtf8("label_id"))
        self.lineEdit_id = QtGui.QLineEdit(self.tab_reset)
        self.lineEdit_id.setGeometry(QtCore.QRect(180, 100, 211, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id.sizePolicy().hasHeightForWidth())
        self.lineEdit_id.setSizePolicy(sizePolicy)
        self.lineEdit_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_id.setObjectName(_fromUtf8("lineEdit_id"))
        self.box_typeReset = QtGui.QComboBox(self.tab_reset)
        self.box_typeReset.setGeometry(QtCore.QRect(180, 130, 211, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_typeReset.sizePolicy().hasHeightForWidth())
        self.box_typeReset.setSizePolicy(sizePolicy)
        self.box_typeReset.setObjectName(_fromUtf8("box_typeReset"))
        self.box_typeReset.addItem(_fromUtf8(""))
        self.box_typeReset.addItem(_fromUtf8(""))
        self.label_typeReset = QtGui.QLabel(self.tab_reset)
        self.label_typeReset.setGeometry(QtCore.QRect(10, 130, 161, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_typeReset.sizePolicy().hasHeightForWidth())
        self.label_typeReset.setSizePolicy(sizePolicy)
        self.label_typeReset.setObjectName(_fromUtf8("label_typeReset"))
        self.box_filename = QtGui.QComboBox(self.tab_reset)
        self.box_filename.setGeometry(QtCore.QRect(180, 160, 211, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_filename.sizePolicy().hasHeightForWidth())
        self.box_filename.setSizePolicy(sizePolicy)
        self.box_filename.setObjectName(_fromUtf8("box_filename"))
        self.label_filename = QtGui.QLabel(self.tab_reset)
        self.label_filename.setGeometry(QtCore.QRect(10, 160, 161, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filename.sizePolicy().hasHeightForWidth())
        self.label_filename.setSizePolicy(sizePolicy)
        self.label_filename.setObjectName(_fromUtf8("label_filename"))
        self.button_reset = QtGui.QPushButton(self.tab_reset)
        self.button_reset.setGeometry(QtCore.QRect(290, 190, 101, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_reset.sizePolicy().hasHeightForWidth())
        self.button_reset.setSizePolicy(sizePolicy)
        self.button_reset.setDefault(True)
        self.button_reset.setObjectName(_fromUtf8("button_reset"))
        self.text_reset = QtGui.QTextBrowser(self.tab_reset)
        self.text_reset.setGeometry(QtCore.QRect(0, 220, 401, 131))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_reset.sizePolicy().hasHeightForWidth())
        self.text_reset.setSizePolicy(sizePolicy)
        self.text_reset.setObjectName(_fromUtf8("text_reset"))
        self.button_refresh = QtGui.QPushButton(self.tab_reset)
        self.button_refresh.setGeometry(QtCore.QRect(10, 190, 121, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_refresh.sizePolicy().hasHeightForWidth())
        self.button_refresh.setSizePolicy(sizePolicy)
        self.button_refresh.setDefault(True)
        self.button_refresh.setObjectName(_fromUtf8("button_refresh"))
        self.tabWidget.addTab(self.tab_reset, _fromUtf8(""))
        self.button_close = QtGui.QPushButton(self.centralwidget)
        self.button_close.setGeometry(QtCore.QRect(314, 400, 101, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setDefault(True)
        self.button_close.setObjectName(_fromUtf8("button_close"))
        GitWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GitWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GitWindow)
        GitWindow.setTabOrder(self.tabWidget, self.box_mode)
        GitWindow.setTabOrder(self.box_mode, self.timeEdit_from)
        GitWindow.setTabOrder(self.timeEdit_from, self.timeEdit_to)
        GitWindow.setTabOrder(self.timeEdit_to, self.spinBox_times)
        GitWindow.setTabOrder(self.spinBox_times, self.dateEdit_date)
        GitWindow.setTabOrder(self.dateEdit_date, self.button_get)
        GitWindow.setTabOrder(self.button_get, self.list_commit)
        GitWindow.setTabOrder(self.list_commit, self.button_createCommit)
        GitWindow.setTabOrder(self.button_createCommit, self.button_status)
        GitWindow.setTabOrder(self.button_status, self.text_status)
        GitWindow.setTabOrder(self.text_status, self.box_merge)
        GitWindow.setTabOrder(self.box_merge, self.box_old)
        GitWindow.setTabOrder(self.box_old, self.box_new)
        GitWindow.setTabOrder(self.box_new, self.lineEdit_old)
        GitWindow.setTabOrder(self.lineEdit_old, self.button_browseOld)
        GitWindow.setTabOrder(self.button_browseOld, self.lineEdit_new)
        GitWindow.setTabOrder(self.lineEdit_new, self.button_browseNew)
        GitWindow.setTabOrder(self.button_browseNew, self.button_patch)
        GitWindow.setTabOrder(self.button_patch, self.button_applyPatch)
        GitWindow.setTabOrder(self.button_applyPatch, self.lineEdit_id)
        GitWindow.setTabOrder(self.lineEdit_id, self.box_typeReset)
        GitWindow.setTabOrder(self.box_typeReset, self.box_filename)
        GitWindow.setTabOrder(self.box_filename, self.button_refresh)
        GitWindow.setTabOrder(self.button_refresh, self.button_reset)
        GitWindow.setTabOrder(self.button_reset, self.text_reset)
        GitWindow.setTabOrder(self.text_reset, self.button_close)

    def retranslateUi(self, GitWindow):
        GitWindow.setWindowTitle(_translate("GitWindow", "Работа с git", None))
        self.box_mode.setItemText(0, _translate("GitWindow", "По дате", None))
        self.box_mode.setItemText(1, _translate("GitWindow", "По количеству", None))
        self.box_mode.setItemText(2, _translate("GitWindow", "В определенный день", None))
        self.label_mode.setText(_translate("GitWindow", "Показать коммиты", None))
        self.label_timeFrom.setText(_translate("GitWindow", "с", None))
        self.timeEdit_from.setDisplayFormat(_translate("GitWindow", "HH:mm dd.MM.yyyy", None))
        self.timeEdit_to.setDisplayFormat(_translate("GitWindow", "H:mm dd.MM.yyyy", None))
        self.label_timeTo.setText(_translate("GitWindow", "по", None))
        self.label_times.setText(_translate("GitWindow", "Число коммитов", None))
        self.dateEdit_date.setDisplayFormat(_translate("GitWindow", "dd.MM.yyyy", None))
        self.label_date.setText(_translate("GitWindow", "Дата коммита", None))
        self.button_get.setText(_translate("GitWindow", "Вывести", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("GitWindow", "Поиск", None))
        self.button_status.setText(_translate("GitWindow", "Показать статус", None))
        self.button_createCommit.setText(_translate("GitWindow", "Создать коммит", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_status), _translate("GitWindow", "Статус", None))
        self.button_patch.setText(_translate("GitWindow", "Редактировать патч", None))
        self.label_old.setText(_translate("GitWindow", "Старый файл", None))
        self.label_new.setText(_translate("GitWindow", "Новый файл", None))
        self.box_merge.setItemText(0, _translate("GitWindow", "Искать файлы", None))
        self.box_merge.setItemText(1, _translate("GitWindow", "Указать вручную", None))
        self.label_merge.setText(_translate("GitWindow", "Слияние", None))
        self.button_browseOld.setText(_translate("GitWindow", "Обзор", None))
        self.button_browseNew.setText(_translate("GitWindow", "Обзор", None))
        self.button_applyPatch.setText(_translate("GitWindow", "Принять", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_merge), _translate("GitWindow", "Слияние", None))
        self.label_text1.setText(_translate("GitWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\">Внимание!</span></p></body></html>", None))
        self.label_text2.setText(_translate("GitWindow", "Откат изменений может нарушить работу Вашей системы.", None))
        self.label_text3.setText(_translate("GitWindow", "Откат к ранним версиям осуществляйте", None))
        self.label_text4.setText(_translate("GitWindow", "на свой страх и риск.", None))
        self.label_id.setText(_translate("GitWindow", "Идентификатор коммита", None))
        self.box_typeReset.setItemText(0, _translate("GitWindow", "Откат всех файлов", None))
        self.box_typeReset.setItemText(1, _translate("GitWindow", "Откат одного файла", None))
        self.label_typeReset.setText(_translate("GitWindow", "Тип отката", None))
        self.label_filename.setText(_translate("GitWindow", "Выберете файл", None))
        self.button_reset.setText(_translate("GitWindow", "Откатить", None))
        self.button_refresh.setText(_translate("GitWindow", "Обновить список", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_reset), _translate("GitWindow", "Откат изменений", None))
        self.button_close.setText(_translate("GitWindow", "Закрыть", None))

