# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created: Mon Feb 18 02:19:21 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(404, 368)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.widget_date = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_date.sizePolicy().hasHeightForWidth())
        self.widget_date.setSizePolicy(sizePolicy)
        self.widget_date.setObjectName(_fromUtf8("widget_date"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_date)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_from = QtGui.QWidget(self.widget_date)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_from.sizePolicy().hasHeightForWidth())
        self.widget_from.setSizePolicy(sizePolicy)
        self.widget_from.setObjectName(_fromUtf8("widget_from"))
        self.formLayout = QtGui.QFormLayout(self.widget_from)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.timeEdit_from = QtGui.QDateTimeEdit(self.widget_from)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_from.sizePolicy().hasHeightForWidth())
        self.timeEdit_from.setSizePolicy(sizePolicy)
        self.timeEdit_from.setMinimumSize(QtCore.QSize(150, 25))
        self.timeEdit_from.setMaximumSize(QtCore.QSize(16777215, 25))
        self.timeEdit_from.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_from.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_from.setCalendarPopup(True)
        self.timeEdit_from.setObjectName(_fromUtf8("timeEdit_from"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.timeEdit_from)
        self.label_timeFrom = QtGui.QLabel(self.widget_from)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timeFrom.sizePolicy().hasHeightForWidth())
        self.label_timeFrom.setSizePolicy(sizePolicy)
        self.label_timeFrom.setMinimumSize(QtCore.QSize(30, 25))
        self.label_timeFrom.setMaximumSize(QtCore.QSize(30, 25))
        self.label_timeFrom.setObjectName(_fromUtf8("label_timeFrom"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_timeFrom)
        self.horizontalLayout.addWidget(self.widget_from)
        self.widget_to = QtGui.QWidget(self.widget_date)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_to.sizePolicy().hasHeightForWidth())
        self.widget_to.setSizePolicy(sizePolicy)
        self.widget_to.setObjectName(_fromUtf8("widget_to"))
        self.formLayout_3 = QtGui.QFormLayout(self.widget_to)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.timeEdit_to = QtGui.QDateTimeEdit(self.widget_to)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_to.sizePolicy().hasHeightForWidth())
        self.timeEdit_to.setSizePolicy(sizePolicy)
        self.timeEdit_to.setMinimumSize(QtCore.QSize(150, 25))
        self.timeEdit_to.setMaximumSize(QtCore.QSize(16777215, 25))
        self.timeEdit_to.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_to.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_to.setCalendarPopup(True)
        self.timeEdit_to.setObjectName(_fromUtf8("timeEdit_to"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.timeEdit_to)
        self.label_timeTo = QtGui.QLabel(self.widget_to)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timeTo.sizePolicy().hasHeightForWidth())
        self.label_timeTo.setSizePolicy(sizePolicy)
        self.label_timeTo.setMinimumSize(QtCore.QSize(30, 25))
        self.label_timeTo.setMaximumSize(QtCore.QSize(30, 25))
        self.label_timeTo.setObjectName(_fromUtf8("label_timeTo"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_timeTo)
        self.horizontalLayout.addWidget(self.widget_to)
        self.gridLayout_3.addWidget(self.widget_date, 1, 0, 1, 1)
        self.widget_buttonGet = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_buttonGet.sizePolicy().hasHeightForWidth())
        self.widget_buttonGet.setSizePolicy(sizePolicy)
        self.widget_buttonGet.setObjectName(_fromUtf8("widget_buttonGet"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_buttonGet)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.button_get = QtGui.QPushButton(self.widget_buttonGet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get.sizePolicy().hasHeightForWidth())
        self.button_get.setSizePolicy(sizePolicy)
        self.button_get.setMinimumSize(QtCore.QSize(100, 25))
        self.button_get.setMaximumSize(QtCore.QSize(100, 25))
        self.button_get.setDefault(True)
        self.button_get.setObjectName(_fromUtf8("button_get"))
        self.gridLayout_2.addWidget(self.button_get, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_buttonGet, 2, 0, 1, 1)
        self.widget_service = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_service.sizePolicy().hasHeightForWidth())
        self.widget_service.setSizePolicy(sizePolicy)
        self.widget_service.setObjectName(_fromUtf8("widget_service"))
        self.gridLayout = QtGui.QGridLayout(self.widget_service)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_statusText = QtGui.QLabel(self.widget_service)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_statusText.sizePolicy().hasHeightForWidth())
        self.label_statusText.setSizePolicy(sizePolicy)
        self.label_statusText.setMinimumSize(QtCore.QSize(75, 25))
        self.label_statusText.setMaximumSize(QtCore.QSize(75, 25))
        self.label_statusText.setObjectName(_fromUtf8("label_statusText"))
        self.gridLayout.addWidget(self.label_statusText, 0, 0, 1, 1)
        self.label_statusService = QtGui.QLabel(self.widget_service)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_statusService.sizePolicy().hasHeightForWidth())
        self.label_statusService.setSizePolicy(sizePolicy)
        self.label_statusService.setMinimumSize(QtCore.QSize(0, 25))
        self.label_statusService.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_statusService.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_statusService.setObjectName(_fromUtf8("label_statusService"))
        self.gridLayout.addWidget(self.label_statusService, 0, 1, 1, 1)
        self.button_stopService = QtGui.QPushButton(self.widget_service)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stopService.sizePolicy().hasHeightForWidth())
        self.button_stopService.setSizePolicy(sizePolicy)
        self.button_stopService.setMinimumSize(QtCore.QSize(80, 25))
        self.button_stopService.setMaximumSize(QtCore.QSize(80, 25))
        self.button_stopService.setDefault(True)
        self.button_stopService.setObjectName(_fromUtf8("button_stopService"))
        self.gridLayout.addWidget(self.button_stopService, 0, 3, 1, 1)
        self.button_startService = QtGui.QPushButton(self.widget_service)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_startService.sizePolicy().hasHeightForWidth())
        self.button_startService.setSizePolicy(sizePolicy)
        self.button_startService.setMinimumSize(QtCore.QSize(80, 25))
        self.button_startService.setMaximumSize(QtCore.QSize(80, 25))
        self.button_startService.setDefault(True)
        self.button_startService.setObjectName(_fromUtf8("button_startService"))
        self.gridLayout.addWidget(self.button_startService, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_service, 0, 0, 1, 1)
        self.list_commit = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_commit.sizePolicy().hasHeightForWidth())
        self.list_commit.setSizePolicy(sizePolicy)
        self.list_commit.setMinimumSize(QtCore.QSize(380, 200))
        self.list_commit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.list_commit.setFont(font)
        self.list_commit.setObjectName(_fromUtf8("list_commit"))
        self.gridLayout_3.addWidget(self.list_commit, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 404, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_main = QtGui.QMenu(self.menubar)
        self.menu_main.setObjectName(_fromUtf8("menu_main"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_configure = QtGui.QAction(MainWindow)
        self.action_configure.setObjectName(_fromUtf8("action_configure"))
        self.action_settings = QtGui.QAction(MainWindow)
        self.action_settings.setObjectName(_fromUtf8("action_settings"))
        self.action_git = QtGui.QAction(MainWindow)
        self.action_git.setObjectName(_fromUtf8("action_git"))
        self.menu_main.addAction(self.action_git)
        self.menu_main.addSeparator()
        self.menu_main.addAction(self.action_configure)
        self.menu_main.addAction(self.action_settings)
        self.menu_main.addSeparator()
        self.menu_main.addAction(self.action_exit)
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_main.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button_startService, self.button_stopService)
        MainWindow.setTabOrder(self.button_stopService, self.timeEdit_from)
        MainWindow.setTabOrder(self.timeEdit_from, self.timeEdit_to)
        MainWindow.setTabOrder(self.timeEdit_to, self.button_get)
        MainWindow.setTabOrder(self.button_get, self.list_commit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "git2etc", None))
        self.timeEdit_from.setDisplayFormat(_translate("MainWindow", "HH:mm dd.MM.yyyy", None))
        self.label_timeFrom.setText(_translate("MainWindow", "с", None))
        self.timeEdit_to.setDisplayFormat(_translate("MainWindow", "H:mm dd.MM.yyyy", None))
        self.label_timeTo.setText(_translate("MainWindow", "по", None))
        self.button_get.setText(_translate("MainWindow", "Вывести", None))
        self.label_statusText.setText(_translate("MainWindow", "Статус:", None))
        self.label_statusService.setText(_translate("MainWindow", "(unknown)", None))
        self.button_stopService.setText(_translate("MainWindow", "Стоп", None))
        self.button_startService.setText(_translate("MainWindow", "Запуск", None))
        self.menu_main.setTitle(_translate("MainWindow", "&Меню", None))
        self.menu_help.setTitle(_translate("MainWindow", "&Справка", None))
        self.action_exit.setText(_translate("MainWindow", "&Выход", None))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_about.setText(_translate("MainWindow", "&О программе", None))
        self.action_configure.setText(_translate("MainWindow", "Настроить &сервис", None))
        self.action_configure.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_settings.setText(_translate("MainWindow", "&Настроить git2etc", None))
        self.action_settings.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.action_git.setText(_translate("MainWindow", "Работа с &git", None))
        self.action_git.setShortcut(_translate("MainWindow", "Ctrl+G", None))

