# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created: Tue Feb 12 22:25:22 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(391, 422)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.timeEdit_from = QtGui.QDateTimeEdit(self.centralwidget)
        self.timeEdit_from.setGeometry(QtCore.QRect(50, 170, 141, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_from.sizePolicy().hasHeightForWidth())
        self.timeEdit_from.setSizePolicy(sizePolicy)
        self.timeEdit_from.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_from.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_from.setCalendarPopup(True)
        self.timeEdit_from.setObjectName(_fromUtf8("timeEdit_from"))
        self.label_timeFrom = QtGui.QLabel(self.centralwidget)
        self.label_timeFrom.setGeometry(QtCore.QRect(10, 170, 31, 21))
        self.label_timeFrom.setObjectName(_fromUtf8("label_timeFrom"))
        self.label_timeTo = QtGui.QLabel(self.centralwidget)
        self.label_timeTo.setGeometry(QtCore.QRect(200, 170, 31, 21))
        self.label_timeTo.setObjectName(_fromUtf8("label_timeTo"))
        self.timeEdit_to = QtGui.QDateTimeEdit(self.centralwidget)
        self.timeEdit_to.setGeometry(QtCore.QRect(240, 170, 141, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_to.sizePolicy().hasHeightForWidth())
        self.timeEdit_to.setSizePolicy(sizePolicy)
        self.timeEdit_to.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_to.setDate(QtCore.QDate(2013, 1, 1))
        self.timeEdit_to.setCalendarPopup(True)
        self.timeEdit_to.setObjectName(_fromUtf8("timeEdit_to"))
        self.button_get = QtGui.QPushButton(self.centralwidget)
        self.button_get.setGeometry(QtCore.QRect(280, 195, 101, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get.sizePolicy().hasHeightForWidth())
        self.button_get.setSizePolicy(sizePolicy)
        self.button_get.setDefault(True)
        self.button_get.setObjectName(_fromUtf8("button_get"))
        self.textBox_get = QtGui.QTextBrowser(self.centralwidget)
        self.textBox_get.setGeometry(QtCore.QRect(10, 220, 371, 151))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox_get.sizePolicy().hasHeightForWidth())
        self.textBox_get.setSizePolicy(sizePolicy)
        self.textBox_get.setObjectName(_fromUtf8("textBox_get"))
        self.label_directory = QtGui.QLabel(self.centralwidget)
        self.label_directory.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.label_directory.setObjectName(_fromUtf8("label_directory"))
        self.lineEdit_ignoreList = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_ignoreList.setGeometry(QtCore.QRect(10, 80, 371, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ignoreList.sizePolicy().hasHeightForWidth())
        self.lineEdit_ignoreList.setSizePolicy(sizePolicy)
        self.lineEdit_ignoreList.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ignoreList.setObjectName(_fromUtf8("lineEdit_ignoreList"))
        self.label_timeSleep = QtGui.QLabel(self.centralwidget)
        self.label_timeSleep.setGeometry(QtCore.QRect(10, 35, 181, 21))
        self.label_timeSleep.setObjectName(_fromUtf8("label_timeSleep"))
        self.lineEdit_timeSleep = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_timeSleep.setGeometry(QtCore.QRect(200, 35, 181, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_timeSleep.sizePolicy().hasHeightForWidth())
        self.lineEdit_timeSleep.setSizePolicy(sizePolicy)
        self.lineEdit_timeSleep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_timeSleep.setObjectName(_fromUtf8("lineEdit_timeSleep"))
        self.label_ignoreList = QtGui.QLabel(self.centralwidget)
        self.label_ignoreList.setGeometry(QtCore.QRect(10, 60, 201, 21))
        self.label_ignoreList.setObjectName(_fromUtf8("label_ignoreList"))
        self.lineEdit_directory = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_directory.setGeometry(QtCore.QRect(170, 10, 211, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_directory.sizePolicy().hasHeightForWidth())
        self.lineEdit_directory.setSizePolicy(sizePolicy)
        self.lineEdit_directory.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_directory.setObjectName(_fromUtf8("lineEdit_directory"))
        self.button_refresh = QtGui.QPushButton(self.centralwidget)
        self.button_refresh.setGeometry(QtCore.QRect(175, 105, 101, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_refresh.sizePolicy().hasHeightForWidth())
        self.button_refresh.setSizePolicy(sizePolicy)
        self.button_refresh.setDefault(True)
        self.button_refresh.setObjectName(_fromUtf8("button_refresh"))
        self.label_statusText = QtGui.QLabel(self.centralwidget)
        self.label_statusText.setGeometry(QtCore.QRect(10, 138, 61, 21))
        self.label_statusText.setObjectName(_fromUtf8("label_statusText"))
        self.label_statusService = QtGui.QLabel(self.centralwidget)
        self.label_statusService.setGeometry(QtCore.QRect(80, 138, 121, 21))
        self.label_statusService.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_statusService.setObjectName(_fromUtf8("label_statusService"))
        self.button_startService = QtGui.QPushButton(self.centralwidget)
        self.button_startService.setGeometry(QtCore.QRect(215, 138, 81, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_startService.sizePolicy().hasHeightForWidth())
        self.button_startService.setSizePolicy(sizePolicy)
        self.button_startService.setDefault(True)
        self.button_startService.setObjectName(_fromUtf8("button_startService"))
        self.button_stopService = QtGui.QPushButton(self.centralwidget)
        self.button_stopService.setGeometry(QtCore.QRect(300, 138, 81, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stopService.sizePolicy().hasHeightForWidth())
        self.button_stopService.setSizePolicy(sizePolicy)
        self.button_stopService.setDefault(True)
        self.button_stopService.setObjectName(_fromUtf8("button_stopService"))
        self.button_apply = QtGui.QPushButton(self.centralwidget)
        self.button_apply.setGeometry(QtCore.QRect(280, 105, 101, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_apply.sizePolicy().hasHeightForWidth())
        self.button_apply.setSizePolicy(sizePolicy)
        self.button_apply.setDefault(True)
        self.button_apply.setObjectName(_fromUtf8("button_apply"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_main = QtGui.QMenu(self.menubar)
        self.menu_main.setObjectName(_fromUtf8("menu_main"))
        self.menu_config = QtGui.QMenu(self.menubar)
        self.menu_config.setObjectName(_fromUtf8("menu_config"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_configfile = QtGui.QAction(MainWindow)
        self.action_configfile.setObjectName(_fromUtf8("action_configfile"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_language = QtGui.QAction(MainWindow)
        self.action_language.setObjectName(_fromUtf8("action_language"))
        self.action_help = QtGui.QAction(MainWindow)
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.menu_main.addAction(self.action_configfile)
        self.menu_main.addSeparator()
        self.menu_main.addAction(self.action_exit)
        self.menu_config.addAction(self.action_language)
        self.menu_help.addAction(self.action_help)
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_main.menuAction())
        self.menubar.addAction(self.menu_config.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "git2etc", None))
        self.timeEdit_from.setDisplayFormat(_translate("MainWindow", "HH:mm dd.MM.yyyy", None))
        self.label_timeFrom.setText(_translate("MainWindow", "с", None))
        self.label_timeTo.setText(_translate("MainWindow", "по", None))
        self.timeEdit_to.setDisplayFormat(_translate("MainWindow", "H:mm dd.MM.yyyy", None))
        self.button_get.setText(_translate("MainWindow", "Вывести", None))
        self.label_directory.setText(_translate("MainWindow", "Рабочая директория:", None))
        self.label_timeSleep.setText(_translate("MainWindow", "Интервал обновления, ч:", None))
        self.label_ignoreList.setText(_translate("MainWindow", "Список игнорируемых файлов:", None))
        self.button_refresh.setText(_translate("MainWindow", "Обновить", None))
        self.label_statusText.setText(_translate("MainWindow", "Статус:", None))
        self.label_statusService.setText(_translate("MainWindow", "(unknown)", None))
        self.button_startService.setText(_translate("MainWindow", "Запуск", None))
        self.button_stopService.setText(_translate("MainWindow", "Стоп", None))
        self.button_apply.setText(_translate("MainWindow", "Применить", None))
        self.menu_main.setTitle(_translate("MainWindow", "&Меню", None))
        self.menu_config.setTitle(_translate("MainWindow", "&Настройки", None))
        self.menu_help.setTitle(_translate("MainWindow", "&Справка", None))
        self.action_configfile.setText(_translate("MainWindow", "Выбрать файл &настроек", None))
        self.action_configfile.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.action_exit.setText(_translate("MainWindow", "&Выход", None))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_language.setText(_translate("MainWindow", "Выбор &языка", None))
        self.action_help.setText(_translate("MainWindow", "&Помощь", None))
        self.action_help.setShortcut(_translate("MainWindow", "F1", None))
        self.action_about.setText(_translate("MainWindow", "&О программе", None))

